### ISSUE TITLE
Javalin integration?

### ISSUE THREAD

**Issue by tipsy** [casid/jte#1]
Hi @casid! I saw your comment over at the Rocker tracker. I would like to offer an "official" modern template engine in [Javalin](https://javalin.io/), would you like to contribut a JTE integration ?

**Comment by casid** [comment]
Hi @tipsy, thanks a lot for the heads up! First off, Javalin is amazing, I'm a fan of your work. That being said, I'd love to contribute an integration of jte for Javalin. I think it should be pretty straight forward. So far, I only used the REST capabilities of Javalin in a small playground project. Are there any hooks for server side rendered pages to plug in to?

My gripe with current template integrations (e.g. Spring MVC) is that they provide a Map<String, Object> context to the templates, which works against all the statically typed benefits of Java, or jte in this case. The site I'm using jte currently puts together a Page object that is then passed to the template engine.

Let me know if there's a repo / place I could hook the jte code into, I'd happily try to write an integration :-)

**Comment by tipsy** [comment]
> Hi @tipsy, thanks a lot for the heads up! First off, Javalin is amazing, I'm a fan of your work. That being said, I'd love to contribute an integration of jte for Javalin. 

Thanks, and thanks! :)

> So far, I only used the REST capabilities of Javalin in a small playground project. Are there any hooks for server side rendered pages to plug in to?

That is the primary purpose of Javalin, the templating support is pretty minimal. The current template implementations consist of one file like this: [JavalinVelocity.kt](https://github.com/tipsy/javalin/blob/master/javalin/src/main/java/io/javalin/plugin/rendering/template/JavalinVelocity.kt)

As well as adding the extension to [JavalinRenderer.kt](https://github.com/tipsy/javalin/blob/master/javalin/src/main/java/io/javalin/plugin/rendering/JavalinRenderer.kt), and an optional dependency in [OptionalDependency.kt](https://github.com/tipsy/javalin/blob/master/javalin/src/main/java/io/javalin/core/util/OptionalDependency.kt)

Once this is in place, Javalin will pick the correct rendering engine based on your extension when you call `ctx.render("/dir/template.ext")`.

> My gripe with current template integrations (e.g. Spring MVC) is that they provide a Map<String, Object> context to the templates, which works against all the statically typed benefits of Java, or jte in this case. The site I'm using jte currently puts together a Page object that is then passed to the template engine.

This is how it currently works in Javalin too, so I guess we'll need to work around that somehow 🤔

**Comment by casid** [comment]
Thanks for providing the starting points! I cloned javalin and it looks all very nice and organized. Also, I'm a fan of the tests for the different template engines :-)

> This is how it currently works in Javalin too, so I guess we'll need to work around that somehow 🤔

While looking at the code I thought about two possible solutions:

1. Put the actual model into the map with a predefined key (pretty hacky, but doesn't require interface changes)
2. Change the signature of the interface to Object, so that an actual POJO can be put in as well (kind of like a JSON serializer would accept both maps and objects...)

I will start a pull request with 1. to see if I can put together anything meaningful and so that you will be able to have a look at it, too - and if it is worth it to change the interface ;-)

**Comment by casid** [comment]
I couldn't resist and put together a pull request for Javalin with basic jte integration:
https://github.com/tipsy/javalin/pull/1034

I went with hacky solution 1 (more about it in the PR).
