### ISSUE TITLE
Output tag parameters on separate lines

### ISSUE THREAD

**Issue by izogfif** [casid/jte#104]
When converting a JSP (or .tag) file containing JTE wrapper tag, produced code ignores attribute / parameter indentation and puts all parameters in a single line. As the result, produced code is harder to read (since sometimes tags can have dozens of parameters).
It would be nice to have an option in JSP converter like "put each parameter on separate line" or at least "apply attribute indentation to parameters" (i.e. if each attribute of the JTE wrapper tag is on a separate line, then output each parameter on a separate line, too).
For example,
```
<jte:jte jte="tag/myTag.jte"
         item="${item}"
         block="${currentBlock}"
         position="${position}"
         nextItem="${nextItem}"
         extraInfo="${extraInfo}"
         urlGenerator="${urlGenerator}"
/>
```
is converted into single line:
```
@tag.myTag(item = item, block = currentBlock, position = position, nextItem = nextItem, extraInfo = extraInfo, urlGenerator = urlGenerator)
```

**Comment by casid** [comment]
I think this isn't an easy one. Would be happy about every PR to improve on it. I currently don't have time to work on it on my own.

**Comment by kelunik** [comment]
IMO this should be solved by a separate formatting tool, not the converter itself.

**Comment by izogfif** [comment]
@casid 
Implemented here: https://github.com/casid/jte/pull/109

**Comment by casid** [comment]
PR is merged, closing this.
