### ISSUE TITLE
Escape strings when converting from JSP EL expression

### ISSUE THREAD

**Issue by izogfif** [casid/jte#106]
If a string inside EL expression has (properly escaped) double quotes inside it, these quotes are written in .jte file unescaped.
For example, JSP file has:
```
${fn:escapeXml(String.format("%s at \"%s\""), person.fullName, company.name)}
```
It's converted to
```
${fn:escapeXml(String.format("%s at "%s""), person.fullName, company.name)}
```
note that quotes around `"%s"` have now become unescaped.

**Comment by casid** [comment]
Thanks for reporting! I pushed a fix for it 👍
