### ISSUE TITLE
JSP Converter - Better c:forEach support

### ISSUE THREAD

**Issue by izogfif** [casid/jte#107]
When converting this JSP code into JTE:
```
<c:forEach var="i" begin="1" end="10" >
   ${i} = ${item}
</c:forEach>
```
I get
```
@for(var i : ???)
   ${i}
@endfor
```
It should be converted into something like this:
```
@for(var forEachStatus : ForSupport.of(IntStream.rangeClosed(1, 10).boxed().toList()))
    !{var i = forEachStatus.get();}
    ${i}
@endfor
```
I think that it would be better to hide `ForSupport.of(IntStream...` behind some custom method like `ForSupport.ofIntList(1, 10)`.
Note: `Stream.toList()` was introduced in Java 16 only.
Well, maybe better even this one:
```
@for(int i = 0; i <= 10; ++i) 
    ${i}
@endfor
```
Note `<=`: JSP `c:forEach`'s `end` is inclusive.
Although I'm afraid it will be hard to convert this Kotlin since Kotlin doesn't have this kind of `for` loops (will have to use ranges, like `@for(i in 0..10)`).

**Comment by casid** [comment]
Proper support for all forEach cases is hard. Right now that conversion needs to be done by hand.

`@for(i in 0..10)` works with jte Kotlin templates as far as I know.

But doing a proper conversion of all foreach possibilities is hard, I think. Would be happy about every PR to improve on it. I currently don't have time to work on it on my own.

**Comment by casid** [comment]
I'm closing this for now - JSP conversion is a one time thing. Also, forEach isn't that frequent and should be possible to convert manually once.
