### ISSUE TITLE
[Question] What to do about @css import?

### ISSUE THREAD

**Issue by KBurgmann** [casid/jte#11]
Hi!

I'd love to use jte for the rendering of our HTML email templates, however the css styling contains an `@import url("https://...");` for a font, which of course is registered as the `@import` keyword from jte.

```css
<style type="text/css" rel="stylesheet" media="all">
    @import url("https://fonts.googleapis.com/css?family=Nunito+Sans:400,700&display=swap"); /* <--- Right here */
    body {
        width: 100% !important;
        height: 100%;
```

Thus, this error is generated:
```
Exception in thread "main" gg.jte.TemplateException: Failed to compile template, error at base-html.jte:14
........./jte-classes/gg/jte/generated/JtebasehtmlGenerated.java:2: error: '.' expected
import url("https://fonts.googleapis.com/css?family=Nunito+Sans:400,700&display=swap");;
          ^
1 error
```

The generated file in turn then also includes the import that was actually meant for rendering in CSS:
```java
package gg.jte.generated;
import url("https://fonts.googleapis.com/css?family=Nunito+Sans:400,700&display=swap");;
public final class JtebasehtmlGenerated {
```

Is there some mechanism to keep these keywords apart, or escape them for jte?

**Comment by casid** [comment]
Hi @KBurgmann, thanks for reporting!

I've written a fix for it, `@import` and `@param` only make sense at the beginning of the template file. As soon as output has been written they are now treated as regular template output: https://github.com/casid/jte/commit/3b0eb1d1c1e67a8cb8bbbc96f1177cc9c6395768 (I took your example for the unit test, hope that's okay 😅)

Still need to teach the IntelliJ plugin to do the same, so that it doesn't look messy in the IDE.

**Comment by casid** [comment]
I just released jte `1.3.0` to maven central - it contains this bugfix. Using that version, at least your template will compile again. Gonna keep you updated about the IntelliJ plugin.

**Comment by kelunik** [comment]
Another way would have been `${'@import url("https://fonts.googleapis.com/css?family=Nunito+Sans:400,700&display=swap");'}`, no?

**Comment by casid** [comment]
Yeah that‘s a good workaround for everything < 1.3 😅

**Comment by casid** [comment]
@KBurgmann the new plugin version got approved by JetBrains: https://plugins.jetbrains.com/plugin/14521-jte/versions/stable/97316

Now the css looks pretty good in the IntelliJ:
<img width="981" alt="After plugin update" src="https://user-images.githubusercontent.com/4077354/93911523-caa82300-fd02-11ea-87fd-18889443c0dc.png">

I'm gonna close this now 👍
