### ISSUE TITLE
Expressions in HTML attribute names are not allowed - can the check be disabled?

### ISSUE THREAD

**Issue by Tim-Hartmann** [casid/jte#111]
I tried using jte together with [alpine.js](https://alpinejs.dev/), which uses the shorthand syntax `@click`, `@keyup`, etc.  for capturing events. I guess jte flags everything starting with `@` as an Expression, causing this snippet
`<div @click.away="open = false" x-data="{ open: false }">`
to error with message in the title.

Using the long-form `x-on:click` instead of `@click` works around the issue.

Is it possible to allow this kind of HTML attribute by default, or at least add an option to allow it?

In any case jte is really easy and fun use :)

**Comment by casid** [comment]
Thanks for the heads up!

I've adjusted the policy to explicitly check for jte keywords and improved the error messages. I'll try to release a new version this weekend :-)

**Comment by casid** [comment]
I just released a new version containing this fix! It's 1.11.2 and should arrive on the maven central caches shortly.
