### ISSUE TITLE
Java and Kotlin lambdas break the parser

### ISSUE THREAD

**Issue by edrd-f** [casid/jte#113]
Hey, it's me again :wave: 

I'm having an issue which breaks the code generator similarly to https://github.com/casid/jte/issues/112.

This time it's happening with Java and Kotlin lambdas. Examples:

###### Lambdas.jte
```
!{var name = java.util.Optional.<String>ofNullable(null)}
${name.map((n) -> { "name: " + n }).orElse("")}
```

Which produces:

```java
public static void render(gg.jte.TemplateOutput jteOutput, gg.jte.html.HtmlInterceptor jteHtmlInterceptor) {
	var name = java.util.Optional.<String>ofNullable(null);
	jteOutput.writeContent("\n");
	jteOutput.writeUserContent(name.map((n) -> { "name: " + n );
	jteOutput.writeContent(").orElse(\"\")}\n");
}
```

While this:

###### Lambdas.kte
```
!{val name: String = null}
${name?.let { "name: $it" } ?: ""}
```

Produces:

```kotlin
@JvmStatic fun render(jteOutput:gg.jte.TemplateOutput, jteHtmlInterceptor:gg.jte.html.HtmlInterceptor?) {
	val name: String? = null
	jteOutput.writeContent("\n")
	jteOutput.writeUserContent(name?.let { "name: $it" )
	jteOutput.writeContent(" ?: \"\"}\n")
}
```

Looks like the parser is accepting the first `}` character as closing the `${}` block.

**Comment by casid** [comment]
@edrd-f I just pushed a fix for this. Out of curiosity: Is this actually a pattern you're using? I never thought someone would use complex lambdas within jte expressions. What you need to keep in mind that any String (in the above example `"name: "` is treated as user input and output escaped.

```
@if(name != null)
  name: ${name}
@endif
```

Here, name: is part of the template and not output escaped. Just something to be aware of.

**Comment by edrd-f** [comment]
Hey @casid, thanks a lot!

The code I was writing at the moment I spotted this issue required generating optional arguments for a function. For example:

```kotlin
fun someGeneratedFunc(${data.argumentType?.let { "name: $it" }}) { /*...*/ }
```

Then, to circumvent the issue, I modified it to:

```kotlin
!{val arguments = if (data.argumentType != null) "name: ${data.argumentType}" else ""}
fun someGeneratedFunc(${arguments}) { /*...*/ }
```

And it seems your suggestion would also work:

```kotlin
fun someGeneratedFunc(@if(data.argumentType != null)name: ${data.argumentType}@endif) { /*...*/ }
```

I didn't even try it because I didn't know it was possible to begin and end JTE expressions on the same line. Nice to know that, as it can be quite handy sometimes :)

The only thing that looks a bit weird is having to stick the string to the closing parens of the `@if` and to the `@endif`, otherwise the extra space is added to the code, which in this example would produce this:

```kotlin
fun someGeneratedFunc( name: SampleType ) { /*...*/ }
```

**Comment by casid** [comment]
Ahh, right. Forgot you're generating Kotlin code. In this case you're using `ContentType.Plain` anyways and there's no output escaping. Thanks for clarifying!

I'll try to release a new version this weekend.

**Comment by izogfif** [comment]
Great to know it's going to be fixed. I had issues with `switch` statements in Java-flavored .jte files.

**Comment by casid** [comment]
@edrd-f version 1.11.4 is on maven central, including this fix 👍

**Comment by edrd-f** [comment]
Thanks!
