### ISSUE TITLE
JTE plugin can't be resolved by Gradle

### ISSUE THREAD

**Issue by IvanPizhenko** [casid/jte#116]
Not sure if you can do something with this, but at least letting you know.

Gradle produces following error:
```
> Could not resolve gg.jte:jte-gradle-plugin:1.11.3. 02:16
         > Could not get resource 'https://plugins.gradle.org/m2/gg/jte/jte-gradle-plugin/1.11.3/jte-gradle-plugin-1.11.3.module'. 02:16
            > Could not GET 'https://jcenter.bintray.com/gg/jte/jte-gradle-plugin/1.11.3/jte-gradle-plugin-1.11.3.module'. 02:16
               > Read timed out
```
Trying `https://jcenter.bintray.com/gg/jte/jte-gradle-plugin/1.11.3/jte-gradle-plugin-1.11.3.module` in browser gives:
```
403 Forbidden
nginx
```

Btw, `jcenter` is many times announced to be shut down and not accepting any new content.

**Comment by IvanPizhenko** [comment]
Update: it's jcenter issue. [Gradle Status](https://status.gradle.com/) now shows following notice:
```
JCenter slow response time
Update - We are continuing to work on a fix for this issue.
Sep 16, 09:54 UTC
Identified - JCenter response time is currently very slow and affects operations on the Gradle plugin portal.
Sep 16, 09:53 UTC

```

**Comment by casid** [comment]
Hmm, I'm uploading to plugins.gradle.org (https://plugins.gradle.org/plugin/gg.jte.gradle). Wasn't aware that they use jcenter() behind the scenes. I think we can't do much about the situation from here. Is it okay to close this issue?

**Comment by IvanPizhenko** [comment]
Yes, can be closed now.
