### ISSUE TITLE
Self contained JAR method for precompiled templates not working?

### ISSUE THREAD

**Issue by roscrl** [casid/jte#117]
Hi casid, trying to package a Javalin app with JTE into a jar using precompiled templates. Reproducible [repo here](https://github.com/roscrl/javalin-test)

Running `mvn install` -> `mvn package` -> `java -jar target/javalin-test-1.0-SNAPSHOT.jar` results in

```
Exception in thread "main" java.lang.NoClassDefFoundError: gg/jte/ContentType
        at App.createTemplateEngine(App.java:27)
        at App.main(App.java:13)
Caused by: java.lang.ClassNotFoundException: gg.jte.ContentType
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 2 more
```

I'm sure this is something silly or my misunderstanding of maven here however.

**Comment by casid** [comment]
Thanks for the example repository and sorry - this info is currently missing the documentation. I cloned your repository and could reproduce the issue. Adding the generated sources with `build-helper-maven-plugin` did the trick for me:

```xml
<!-- Add the generated sources, so that they get compiled -->
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>build-helper-maven-plugin</artifactId>
    <executions>
        <execution>
            <phase>generate-sources</phase>
            <goals>
                <goal>add-source</goal>
            </goals>
            <configuration>
                <sources>
                    <source>${project.build.directory}/generated-sources/jte</source>
                </sources>
            </configuration>
        </execution>
    </executions>
</plugin>
```

According to this [stackoverflow post](https://stackoverflow.com/questions/19633505/why-are-maven-generated-sources-not-getting-compiled) it is possible to add the generated sources directly through the jte maven plugin. This way we wouldn't need the build helper plugin. I'll give it a try and keep you updated!

Also, it's nice to see you're using jte together with hotwire. That should be a really nice combination :-)

**Comment by casid** [comment]
Sorry, my previous answer was just plain wrong. This is a classloader problem, because the built jar file doesn't contain dependencies. Adding this to your pom.xml did the trick for me:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-assembly-plugin</artifactId>

    <configuration>
        <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
        </descriptorRefs>
        <archive>
            <manifest>
                <addClasspath>true</addClasspath>
                <mainClass>App</mainClass>
            </manifest>
        </archive>
    </configuration>

    <executions>
        <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
                <goal>single</goal>
            </goals>
        </execution>
    </executions>

</plugin>
```

Also, awesome that you're using jte together with hotwired :-)
