### ISSUE TITLE
[DOCS] Please, provide a kotlin build.gradle.kts sample in documentation

### ISSUE THREAD

**Issue by dodalovic** [casid/jte#119]
![image](https://user-images.githubusercontent.com/6358061/141681195-29b0395a-960f-4765-b06b-12ad5166fbc1.png)

**Comment by casid** [comment]
@dodalovic thanks for reporting!

Unfortunately, I'm a complete noob when it comes to gradle. The gradle plugin was mostly contributed by @rferreira and @edward3h. Maybe they can provide help there.

If not and you find out how to do this with Kotlin DSL, I'd be glad for any update!

**Comment by edward3h** [comment]
The snippet being referred to is not a top level block in the gradle build, which probably contributes to the confusion. I'll see if I can improve the example.

**Comment by casid** [comment]
Aww, wow that was quick! Thanks for looking into it @edward3h!
