### ISSUE TITLE
@threadSafe in maven error

### ISSUE THREAD

**Issue by Tankonyako** [casid/jte#123]
Warn in console:
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in sbd:
[WARNING] gg.jte:jte-maven-plugin:1.12.1
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```
Also i have problem resources (compiled classes) not including in jar, only 50% files.

**Comment by casid** [comment]
Hi @Tankonyako!

I marked the jte plugin as @threadSafe, according to the [Mojo thread safety assertion checklist](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3).

Can you please post how you setup jte in you pom.xml? What does only 50% files mean?

**Comment by Tankonyako** [comment]
> Hi @Tankonyako!
> 
> I marked the jte plugin as @threadsafe, according to the [Mojo thread safety assertion checklist](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3).
> 
> Can you please post how you setup jte in you pom.xml? What does only 50% files mean?

Why im also getting warn about @threadsafe?
I meant that when building a project, all templates are generated in the-classes, but only half gets into the finished jar file, and because of this I have to compile the project several times

**Comment by casid** [comment]
Because, you probably don't use the latest snapshot build yet, where the warning doesn't appear anymore.

The jte maven plugin has no global state and it should be possible to invoke it for different modules in parallel.

Your issue might be a problem with the dependency graph of your modules. But this is hard to tell, without seeing how you setup jte in your pom.xml.

**Comment by casid** [comment]
I'm closing this issue for now. If you have more information, please reopen it.
