### ISSUE TITLE
micronaut-views integration

### ISSUE THREAD

**Issue by edward3h** [casid/jte#124]
Just an FYI I'm working on micronaut-views integration. In case someone else had the same idea...

https://github.com/micronaut-projects/micronaut-views/pull/320

**Comment by casid** [comment]
Oh nice! I haven't tried micronaut yet, but heard good things about it.

Will definitely have an eye on this :-)

**Comment by edward3h** [comment]
And, it's now an option in Micronaut Launch https://micronaut.io/launch so maybe people will see it and be curious.

**Comment by casid** [comment]
Wow, that's awesome. Congratulations!

Thanks @edward3h for the hard work you put into this!

**Comment by casid** [comment]
I added a link to the [micronaut integration](https://micronaut-projects.github.io/micronaut-views/latest/guide/#jte) to the list of frameworks [here](https://github.com/casid/jte#framework-integration).
