### ISSUE TITLE
Question: How to escape the template engine syntax?

### ISSUE THREAD

**Issue by renannprado** [casid/jte#125]
For example, let's say I have an HTML page that has some inline javascript, like the below one.

```javascript
console.log(`testing ${myVar}`);
```
How can I escape the `jte` syntax so to say, in that piece of code, to make sure it won't be processed?

**Comment by kelunik** [comment]
```jte
console.log(`testing ${"${myVar}"}`);
```

Usually using a string is the easiest way, I think.

**Comment by renannprado** [comment]
@kelunik thanks. That would work. However, it would be really nice if there was a real escape feature.

**Comment by renannprado** [comment]
@casid so if I understood correctly, there won't be a way to do the escape then? I mean, when we mix jte with some more complex things like react or vue, couldn't it be it would be more problematic?

**Comment by casid** [comment]
@renannprado I don't think it is worth the extra complexity. Also, I don't think jte will be used to generate vue/react files, right?

For the Javascript example above, it would also be possible to use a unicode escape sequence.

**Comment by renannprado** [comment]
> Also, I don't think jte will be used to generate vue/react files, right?

@casid  I'm not sure if that would be realistic tbh. Let's say it's not. 

Still I do believe it's realistic to mix _javascript_ in the same file (even if it's small bits) or could be that I'm old-fashioned and like to use jquery with the dollar sign. You can argue of course that these things belong to a different non-jte-file, that would be a workaround/solution as well. `jte` is great, really. Maybe my examples are not convincing enough, but a do believe that would a nice addition to the engine. 

> I don't think it is worth the extra complexity

I understand what you're saying here. Do you think we could come up with a design that doesn't add too much complexity?

Without knowing the codebase, and whether that would be too complex to implement, I would imagine something like the below (as opposed to the escape sequence I suggested in the beginning):

```js
// the below code is not processed by JTE
@skip
const myVar = "abc123";
console.log(`test ${myVar}`);
@endskip
```
or even based on "annotations"/comments (maybe this one would be more difficult):

```js
// the below code is not processed by JTE
// @jteskip
const myVar = "abc123";
console.log(`test ${myVar}`);
// @endjteskip
```

If you're still not convinced, no problem :smile: , there are workarounds anyway.

**Comment by casid** [comment]
For the escape sequence I meant something like this:

```javascript
const myVar = "abc123";
console.log(`test \x24{myVar}`);
```

I think technically it would not be that hard to introduce such a non-template block. However, the philosophy is to have as least keywords in the template language as possible. And as said, I'm not entirely convinced this is necessary, as there are other workarounds to do the same.

**Comment by casid** [comment]
@renannprado I'm currently working on a feature, that allows to call templates from any directory, not just `/tag` or `/layout` (https://github.com/casid/jte/pull/126).

To avoid unwanted template calls, on this branch I introduced an escape sequence for `@`, namely `@@` is renderer as `@`.

For the sake of symmetry, we could do the same with `${}`, so `$${}` would be rendered as `${}`.

Would that be a solution for this issue?

**Comment by renannprado** [comment]
@casid I cannot elaborate too much as I'm writing from my phone, but while that would be a solution what I'm thinking is about IDE syntax support. It would be nice to see how it behaves in this situation (for the sake of having auto completion inside of `$${}`, that is). IDK how this syntax with the plugin.

I'm happy that you're considering it!

**Comment by casid** [comment]
@renannprado I tried a few things with the IntelliJ plugin today and `$${}` really reads a little awkward. I thought about what keyword would fit this usecase best. I think I'd really like `@raw` for this, since this is the actual intend. We want the raw, unprocessed output, without any template engine interaction.

```xml
@raw
my stuff here ...
@endraw
```

What do you think? I'll give it a try as soon as I can.

**Comment by kelunik** [comment]
`@verbatim` might be an alternative, but `@raw` is shorter.

**Comment by renannprado** [comment]
@casid IMHO `@raw` is good enough! If you'd like to be a bit more verbose I thought of `@engineoff`/`@endengineoff`.

One caveat I just thought of now is how jte would deal with such code?

```javascript
@raw
/**
 * @param ....
 */
function myFunc(x) {
@endraw
```

**Comment by renannprado** [comment]
@casid just a random I thought I had now, might be stupid idea: as you're about to release a version 2.x, it could be it's a good idea to use `@@` instead of `@` as jte's "reserved char". It is much less likely jte is going to run into such issues.

**Comment by casid** [comment]
@renannprado `@param` shouldn't be problem, even today. It's only allowed at the very beginning of a template and ignored afterwards.

Also, I think `@raw` would disable all template engine processing, so all jte keywords within it are simply ignored.

**Comment by casid** [comment]
I think I got a first draft for jte and the IntelliJ plugin.

![raw-intellij](https://user-images.githubusercontent.com/4077354/151750912-8679fe73-397b-4ff1-9371-068471f334e7.png)

**Comment by renannprado** [comment]
> @renannprado `@param` shouldn't be problem, even today. It's only allowed at the very beginning of a template and ignored afterwards.
> 
> Also, I think `@raw` would disable all template engine processing, so all jte keywords within it are simply ignored.
> 
> > @casid just a random I thought I had now, might be stupid idea: as you're about to release a version 2.x, it could be it's a good idea to use @@ instead of @ as jte's "reserved char".
> 
> I don't know, it would at the same time make the whole language a lot more verbose.

Makes sense... As long as you don't need to write `@endraw` then anything reserved by jte would be ignored in that block.

**Comment by renannprado** [comment]
@casid sorry for the delay.

I've tested both the plugin and the new version of `jte` and it seems to be working well.

The only thing I noticed is that inside of the `@raw` block, the plugin still offers things like `@for` from `jte` in the autocompletion.
That would be a nitpick though. IMHO the most important thing is that the language injection, in that case, javascript is working well with the plugin :+1: .

![image](https://user-images.githubusercontent.com/2359543/154857263-232c4ca9-d89d-4842-bf4d-92b450c4bc00.png)

**Comment by casid** [comment]
Thanks for giving it a shot!

Yeah, the autocompletion is done via live templates, I think to prevent those they'd need to be implemented by hand.

**Comment by casid** [comment]
@renannprado jte 2 is finally released, containing this feature!

I've updated the documentation this morning, so I think everything's done now.

Thank you for suggesting this feature and sorry it took so long! But I really like the end result :-)

**Comment by unoexperto** [comment]
@casid First of all thank you so much for great library!

I just stumbled upon this "issue" and I feel like @raw solution is a bit akward to avoid escaping $ character. I'm genreating maven pom.xml file and maven uses variables the same way you do so it's

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.xxx.xxx</groupId>
        <artifactId>xxx-sdk</artifactId>
        <version>${value.xxxSdkVersion}</version>
      </dependency>
@raw
      <dependency>
        <groupId>com.xxx.system.code</groupId>
        <artifactId>system-code-gladiator-ml</artifactId>
        <version>${system-code-gladiator-ml.version}</version>
      </dependency>
      <dependency>
        <groupId>io.swagger.core.v3</groupId>
        <artifactId>swagger-annotations</artifactId>
        <version>${swagger-annotations-version}</version>
      </dependency>
      <dependency>
        <groupId>javax.annotation</groupId>
        <artifactId>javax.annotation-api</artifactId>
        <version>${javax.annotation-api-version}</version>
      </dependency>
@endraw
    </dependencies>
  </dependencyManagement>
```

It's not terribly bad but still a bit weird to me to wrap section of XML just because of a need to escape one character.

**Comment by kelunik** [comment]
@unoexperto You can still use the initial suggestion to escape a single character:

```jte
<version>${"$"}{javax.annotation-api-version}</version>
```
