### ISSUE TITLE
@template is treated like a string

### ISSUE THREAD

**Issue by schlumpfling42** [casid/jte#129]
Hi,

I'm using jte 1.12.1 and trying to use a template like this:
    "${attributeName}" : @template.test()
and it gets compiled into
    jteOutput.writeUserContent(attributeName);
    jteOutput.writeContent("\" : @template.test()\r\n");

Is this a bug or am I doing something wrong?

**Comment by kelunik** [comment]
You'll have to use `@layout` / `@tag` in 1.x, `@template` will be the more generic syntax in 2.x.

**Comment by casid** [comment]
Dang, when I merged the 2.0 branch I already updated the syntax documentation to @template.

@schlumpfling42 you can start right away with `@tag`, once 2.0 is out, there's gonna be an automatic migration the new syntax.

**Comment by casid** [comment]
I've updated the [documentation](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#template-calls)! Sorry about the confusion and thanks for reporting this.
