### ISSUE TITLE
Qute comparison?

### ISSUE THREAD

**Issue by newk5** [casid/jte#132]
How does jte compare to [qute](https://quarkus.io/guides/qute), performance-wise?

**Comment by casid** [comment]
For a general comparison to Qute, have a look at [this issue](https://github.com/casid/jte/issues/49).

Performance-wise I have no idea. If Qutes expression language runs interpreted it is surely going to be slower than jte, which compiles to Java classes. From the various Java template engines [in this benchmark](https://github.com/casid/template-benchmark/) jte is the fastest.

The only way to find out would be adding Qute to that benchmark. Do you know if Qute can be used without Quarkus? That would be extremely helpful for the benchmark.

**Comment by newk5** [comment]
Yea qute can be used standalone without quarkus, check here: https://quarkus.io/guides/qute-reference#standalone

**Comment by casid** [comment]
Added qute to the benchmark: https://github.com/casid/template-benchmark/commit/12aaa76819c45f7aa83f4302c0c1395a3578b645

I did a quick run (JDK 11, AMD Ryzen 5950x, Single Core). In that benchmark, jte is about 10x faster than Qute.

In the real world the differnce might be bigger. The benchmarked template doesn't contain a lot of expressions (one for loop, two ifs).

**Qute**
```
# Fork: 1 of 5
# Warmup Iteration   1: 22607,704 ops/s
# Warmup Iteration   2: 23272,991 ops/s
# Warmup Iteration   3: 23319,096 ops/s
# Warmup Iteration   4: 23281,413 ops/s
# Warmup Iteration   5: 23144,662 ops/s
Iteration   1: 23295,953 ops/s
Iteration   2: 23279,231 ops/s
Iteration   3: 23255,398 ops/s
Iteration   4: 23245,303 ops/s
Iteration   5: 23271,195 ops/s
```

**jte**
```
# Run progress: 0,00% complete, ETA 00:12:30
# Fork: 1 of 5
# Warmup Iteration   1: 222484,518 ops/s
# Warmup Iteration   2: 224371,615 ops/s
# Warmup Iteration   3: 224257,117 ops/s
# Warmup Iteration   4: 224204,182 ops/s
# Warmup Iteration   5: 224438,868 ops/s
Iteration   1: 224081,393 ops/s
Iteration   2: 223820,053 ops/s
Iteration   3: 224012,247 ops/s
Iteration   4: 224180,216 ops/s
Iteration   5: 224542,812 ops/s
```

**Comment by newk5** [comment]
Ah cool, that's interesting, thanks for benchmarking it. Jte looks impressive.

**Comment by casid** [comment]
Thanks!
