### ISSUE TITLE
HTML over the wire api?

### ISSUE THREAD

**Issue by bowbahdoe** [casid/jte#134]
Hi, new to the project.

This might sound silly, but how feasible would it be to make templates usable with a Phoenix live view style HTML over the wire system?

**Comment by casid** [comment]
I think this should work very well.

jte is very lightweight and templates can be rendered from anywhere (unlike say JSP, which need forwards to the JSP servlet).

In case you want to send small HTML snippets over websockets or server sent events, the jte engine can render any template file in your project individually. I think in the end that's the only thing you need to achieve what you're looking for.

**Comment by roscrl** [comment]
@bowbahdoe Just as example I recently tried unpoly & turbo with jte. No issues at all, still not sure on the best structure yet but see this small project for [examples](https://github.com/roscrl/econicles/tree/main/src/main/resources/views)
