### ISSUE TITLE
Native image build fails (JDK 11, windows-latest)

### ISSUE THREAD

**Issue by casid** [casid/jte#135]
Just noticed that the native image build fails since yesterday. Only JDK 11 / Windows seems to be affected.

```
Execution failed for task ':nativeImage'.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> Couldn't find an installation of Windows SDK 7.1 suitable for GraalVM.
```

**Comment by edward3h** [comment]
There is already some custom logic for the nativeImage test build in https://github.com/casid/jte/blob/master/test/jte-runtime-cp-test-gradle-convention/build.gradle#L63

(I'm assuming this is the one that is being hit).
You shouldn't need to remove JDK 11 builds for the whole project.

I should revisit this: GraalVM has dropped JDK 8 support and picked up JDK 17 support.

**Comment by casid** [comment]
Thanks for looking into it! I'll reopen this then.

**Comment by edward3h** [comment]
So this is probably relevant https://github.com/actions/virtual-environments/issues/4856
I'll test with windows-2019

**Comment by edward3h** [comment]
windows-2019 passes.

So there's an incompatibility with windows-2022, either with GraalVM itself or the Palantir Graal gradle plugin.

**Comment by edward3h** [comment]
Looks like the Palantir plugin checks for VS version 2019 or 2017 
https://github.com/palantir/gradle-graal/blob/develop/src/main/java/com/palantir/gradle/graal/GraalExtension.java

(I basically never use Windows myself so my appetite for trying to work around this is low. I think that Graal native images are usually going to be used in Docker anyway.)

**Comment by casid** [comment]
Thanks for looking into it! Totally agree with you, I'm closing this now, as windows-2019 is a good workaround for the CI build.
