### ISSUE TITLE
FAQ for comparisons

### ISSUE THREAD

**Issue by sigzero** [casid/jte#136]
If this is more or less a JSP replacement (and it looks like that to me) there should be an FAQ or discussion point somewhere about why one would use jte (or jte2) versus a jsp.

**Comment by casid** [comment]
Welcome @sigzero!

Glad you're asking! I've written a fair amount of JSP code and some pain points with JSP caused the creation of jte. IMHO the most compelling reasons are:
- [Context sensitive output escaping](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#html-escaping) at compile time (for me, this alone is a killer feature)
- [Smart HTML attribute](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#smart-attributes) handling saves a lot of time and cleaner templates
- No EL expression overhead, basically zero performance overhead through the template engine
- Type safety at compile time, no unknown property exceptions at runtime
- High concurrency, there are no locks like in various internal JSP classes
- Lightweight setup and small library footprint, there's no servlet container required, so jte can easily used for other templating jobs besides websites like mails, pdfs, etc.

Most compelling reasons against jte:
- JSPs have been around for a long time and the technology won't go away all of a sudden
- There are currently only a few people working on jte
- While the IntelliJ plugin is pretty good to work with, it is not maintained by Jetbrains and future IntelliJ updates could cause friction

Hope this helped! And thanks for checking out the project :-)
