### ISSUE TITLE
Optional imports/parameter declaration

### ISSUE THREAD

**Issue by newk5** [casid/jte#138]
Hello, are parameters strictly obligatory? With Qute, parameter declaration is [optional](https://quarkus.io/guides/qute#template-parameter-declaration-inside-the-template-itself), I like that I can basically just do:
```java
template.data("pojo", pojoInstance).render();
```
And in my HTML page I can just acess the "pojo" variable without doing any imports or any parameter declaration. Are imports and parameter declarations always required with JTE?

JTE's performance is very atractive but I think usabillity seems to be not on par with qute or pebble, which dont require imports or parameter declaration.

**Comment by kelunik** [comment]
You can always declare a `Map` to store arbitrary data without declaring additional parameters. You can also give parameters a default value if you want to make them optional, I think it's `= <default>` after the parameter declaration.

**Comment by newk5** [comment]
What I mean by "optional" is: not being necessary to declare at all in the template file, just declare them once in the java code. Like with qute you just pass the parameter name with the .data(paramName, paramValue) method. With JTE you have to pass the parameter to the template in java code and also have to declarate it inside the template file itself, its this repetition I want to avoid

**Comment by casid** [comment]
See, this is IMHO the biggest advantage of jte over qute. Once your project gets bigger you will be a lot more productive with jte, given you use it with the IntelliJ plugin. Without the plugin, you won't have much fun with jte, that's for sure. But for the type safe experience the plugin provides, you just have to pay the price to declare types and variables, otherwise the IDE won't be able to help you with autocomplete and refactorings.

Just imagine you are using a qute "global" variable in a few layer deep nested template hierarchy. You will have no idea what type is, where it comes from, and good luck renaming it or removing it from where you set it on the Java side.

It's a matter of taste maybe, but being type safe is jte's big USP to other template engines. Personally I think this fits very well with Java. There's no way to give up on this. If you really want to give up type safety, jte is the wrong template engine for your needs.

**Comment by newk5** [comment]
Type safe templates are also possible with Qute when you declare your parameters, but since they're optional, it lets the users choose. I can choose whether I want type safety, or whether I want to be more productive and avoid declaring parameters twice and just declare them once in java code. I was hoping jte allowed making this choice too but with jte it seems they are always required. In Qute if I'm using a global variable I can easily find out its type if I just look at the java code, at the moment where I'm passing variables to the template I can just check there directly in java code, which in my opinion is preferable to checking variables types in template files.

Type safety has some advantages as you mentioned, when it comes to IDE support and possible refactoring too, it makes things easier, but in my opinion the usability takes a big hit. Having to declare parameters and imports in every .jte file after you already declared them in java code is time consuming and we just end up repeating ourselves.

But I understand, maybe this is just the price to pay for good performance. I was looking for a qute alternative but faster, so I was trying out jte but the non-optional imports/parameters are not viable for my use cases, maybe pebble is my best option.

**Comment by casid** [comment]
Maybe you're using jte different than me. I usually pass just one page object for each page I'm rendering. That takes a few seconds and from there on I can add properties to that page as needed. And from there on there is no template engine that provides me the same level of usability in IntelliJ. For example:

![image](https://user-images.githubusercontent.com/4077354/156912420-6ac6b8e2-ba8b-411b-9d9a-6a679bbdc5bc.png)

**Comment by newk5** [comment]
Yea I'm a Netbeans user so I cant make use of the plugin, which is why my usability is not so good plus having to declare imports and params for every file.

**Comment by casid** [comment]
Ah, that makes sense!

Yes, without a plugin jte is a pain to work with. In that setup I can't recommend using jte.

**Comment by newk5** [comment]
I use Qute without a plugin too and I find it very pleasant to use. I think jte too would be just as pleasant to use even without a plugin if the imports/params were optional/non-obligatory, but I see your point, the plugin does help alot.
