### ISSUE TITLE
simple basic layout example?

### ISSUE THREAD

**Issue by torian257x** [casid/jte#139]
hi

I generally like what I see.

What I don't understand though is... how do you actually create a basic layout with say, body and footer?

I read here
https://github.com/casid/jte/blob/master/DOCUMENTATION.md#content

```
@import org.example.WelcomePage
@param WelcomePage welcomePage

@template.layout.page(
    page = welcomePage,
    content = @`
        <p>Welcome, ${welcomePage.getUserName()}.</p>
    `,
    footer = @`
        <p>Thanks for visiting, come again soon!</p>
    `
)
```

this is how you create it?

I mean, assuming you dont have a single <p> line?

or do you somehow combine the "variable declaration" with the @``?

is there like an example of a proper simple layout - that is not just ONE page, but a few pages sharing same layout etc.

**Comment by casid** [comment]
Welcome!

It's possible to have multiple lines in a content block.

```html
@import org.example.WelcomePage
@param WelcomePage welcomePage

@template.layout.page(
    page = welcomePage,
    content = @`
        <div>
             <div>...</div>
             <div>...</div>
             <div>...</div>
             <div>...</div>
        </div>
    `,
    footer = @`
        <div>
             <div>...</div>
             <div>...</div>
        </div>
    `
)
```

**Comment by casid** [comment]
Yes, the full power of jte can be used within content blocks. You can think of them like lambdas in Java. And yes, you can nest them :-)

Your example would work different, though.

_membersLayout.jte_
```html
@param gg.jte.Content content

@template.appLayout(
    content = content,
    footer = @`
        <p>this is footer member</p>
    `
)
```

_membersDashboard.jte_
```html
@template.membersLayout(
    content= @`
        <p>This is content</p>
    `
)
```
