### ISSUE TITLE
Inline java code?

### ISSUE THREAD

**Issue by torian257x** [casid/jte#140]
is it possible to inline java code snippets?

It's possible to do this in all good major templating engines. E.g. https://laravel.com/docs/9.x/blade or c# razors. Blazor as well.

People claiming that this "opens the gates to hell" are just wrong imho. You can open the gates to hell one way or another. But handing adults baby scissors with rounded points out of fear a toddler might ram it into his eye ball isnt a good excuse.

**Comment by casid** [comment]
Anything within `!{}` is executed as Java code. Mostly this is used for variables, like

```
!{var foo = "test";}

Used here: ${foo}
And here: ${foo}
And there: ${foo}
```

**Comment by torian257x** [comment]
ah thank you, I think I missed it on the second read (I thought I saw something the first time I looked at it, thus I'm still here)

this does support multi line I assume? I guess all of your expressions do?

**Comment by casid** [comment]
Yes it is, although I never had a usecase for it.
