### ISSUE TITLE
Why is it recommended to have an external folder with jte-classes?

### ISSUE THREAD

**Issue by roscrl** [casid/jte#142]
The docs suggest to have your compiled classes in an external folder https://github.com/casid/jte/blob/master/DOCUMENTATION.md#using-a-directory-on-your-server-recommended

What is the advantage of that over just shoving them in along with the jar files?

It be great if you left the targetDirectory property empty on the jte-maven-plugin that it would bundle the compiled classes into the jar and work with `var templateEngine = TemplateEngine.createPrecompiled(ContentType.Html); `

Currently if you leave out the targetDirectory property the plugin fails with a null pointer exception.

**Comment by casid** [comment]
Welcome! You can create a self contained JAR by using the `generate` task of the maven plugin:

https://github.com/casid/jte/blob/master/DOCUMENTATION.md#using-the-application-class-loader-since-120

The limitations of this approach are listed there as well.

**Comment by roscrl** [comment]
Doh! Apologies, thanks for the quick response!

**Comment by casid** [comment]
No worries, you're welcome!
