### ISSUE TITLE
No gradle plugin for 2.0.2?

### ISSUE THREAD

**Issue by spinscale** [casid/jte#143]
https://plugins.gradle.org/plugin/gg.jte.gradle does not show a gradle plugin for 2.0.2.

Unsure if a bug or a feature and we can just roll with 2.0.1 as plugin version? :-)

**Comment by yusukezzz** [comment]
Current latest release is 2.0.1 (2.0.2 is next development version).

But only the gradle plugin seems to be missing version 2.0.1.

404 -> https://mvnrepository.com/artifact/gg.jte/jte-gradle-plugin/2.0.1

**Comment by casid** [comment]
@spinscale sorry, that was my bad! I've published 2.0.1 gradle plugin now.

@yusukezzz you're right, the missing version is 2.0.1.

**Comment by spinscale** [comment]
worked, thanks for the quick fix!
