### ISSUE TITLE
Ability to not automatically remove comments 

### ISSUE THREAD

**Issue by odeits** [casid/jte#146]
In order to use jte to write email templates I need to have comments in the html. This is automatically generated for me using mjml. I would like to have a mode or option when precompiling to not automatically remove these comments so I do not have to go in and manually wrap all of that in raw tags.

```
<!--[if mso]>stuff in here<![endif]-->
<!--[if !mso]>[fallback goes here]<![endif]-->
```

**Comment by casid** [comment]
Welcome!

This should be possible by setting htmlCommentsPreserved to true. I just checked the maven plugin, this option is exposed there.

**Comment by odeits** [comment]
Perfect! This did exactly what I needed it to!
