### ISSUE TITLE
Allow default components tags?

### ISSUE THREAD

**Issue by roscrl** [casid/jte#150]
Hi casid, working on a [small project with JTE](https://github.com/roscrl/econicles/tree/f0592b67047d7cceca1666e139699c8e0f0c92af)

I came across this while extracting pages to layouts 

```
@param String title = "Econicles"
@param gg.jte.Content searchBar
@param gg.jte.Content content

<!DOCTYPE html>
<html lang="en" class="overflow-x-hidden">

<body>

@template.components.head(title = title)

${searchBar}

${content}

</body>

</html>
```

searchBar is a component/tag, it would be really cool if I could have default components such where
``` @param gg.jte.Content searchBar = @`@template.components.searchBar(autofocus = true)` ```

Unless there is a way to already do this or you have a suggestion to work around having to repeat searchBar component within other pages like [not_found.jte](https://github.com/roscrl/econicles/blob/f0592b67047d7cceca1666e139699c8e0f0c92af/src/main/resources/views/pages/not_found.jte) [too_many_requests.jte](https://github.com/roscrl/econicles/blob/f0592b67047d7cceca1666e139699c8e0f0c92af/src/main/resources/views/pages/too_many_requests.jte) but having to have a unique instance for [stock_view.jte](https://github.com/roscrl/econicles/blob/f0592b67047d7cceca1666e139699c8e0f0c92af/src/main/resources/views/pages/stock_view.jte) which passes more info to searchBar component/tag

**Comment by casid** [comment]
Nice, thank you for the follow-up!
