### ISSUE TITLE
Incorrect rendering with comments on same line

### ISSUE THREAD

**Issue by roscrl** [casid/jte#151]
https://user-images.githubusercontent.com/13072760/167739747-5e4d5212-3b0a-4e1c-b229-1af5debf2b1f.mp4

Hopefully video explains, I think this is an issue with jte? Or maybe some crazy js thing?

**Comment by casid** [comment]
Thanks for reporting, that was definitely an issue with jte. While removing the js comment, the line break at the end got removed as well :-/ (this is the fix: https://github.com/casid/jte/commit/a31baca35eb17fb2451751dfa178e96ab683dca5)

Fix will be part of the 2.0.3 release.
