### ISSUE TITLE
Gradle plugin for 2.0.3 throws not found errors

### ISSUE THREAD

**Issue by spinscale** [casid/jte#154]
When trying to use the 2.0.3 gradle plugin I get:

```
 ./gradlew clean check

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'elasticcc-app'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find jte-kotlin-2.0.3.jar (gg.jte:jte-kotlin:2.0.3).
     Searched in the following locations:
         https://plugins.gradle.org/m2/gg/jte/jte-kotlin/2.0.3/jte-kotlin-2.0.3.jar
   > Could not find jte-2.0.3.jar (gg.jte:jte:2.0.3).
     Searched in the following locations:
         https://plugins.gradle.org/m2/gg/jte/jte/2.0.3/jte-2.0.3.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 296ms
```

My gradle setup is (just for reference, maybe I did something stupid without realising...):

```
plugins {
    id 'application'
    id "com.github.ben-manes.versions" version "0.42.0"
    id "gg.jte.gradle" version "2.0.3"
    id 'de.thetaphi.forbiddenapis' version '3.3'
}

repositories {
    mavenCentral()
}
```

**Comment by casid** [comment]
Hmm, my last deployment to maven central didn't show any errors. I just had a quick look and at least there's something there :-D https://repo1.maven.org/maven2/gg/jte/jte-kotlin/2.0.3/

I just had a closer look at the error message and it looks like gradle is looking for jte-kotlin in the gradle plugin repository, which probably doesn't exist there.

I assume the exact same config works with 2.0.2, right?

**Comment by casid** [comment]
Interesting,

This exists:
https://plugins.gradle.org/m2/gg/jte/jte-kotlin/2.0.2/jte-kotlin-2.0.2.jar

This does not:
https://plugins.gradle.org/m2/gg/jte/jte-kotlin/2.0.3/jte-kotlin-2.0.3.jar

Both links eventually redirect to a artifactory server, like the 2.0.2 one: https://repo.gradle.org/ui/native/jcenter/gg/jte/jte-kotlin/2.0.2/jte-kotlin-2.0.2.jar

Maybe this cache is not up-to-date yet?

**Comment by spinscale** [comment]
Adding the following to `settings.gradle` works to make sure those jars can be looked up from maven central

```
pluginManagement {
  repositories {
    mavenCentral()
    gradlePluginPortal()
  }
}
```

**Comment by spinscale** [comment]
Regarding your question about the exact same config: Exactly, only changed the versions.

**Comment by yusukezzz** [comment]
Was it a cache issue? I can retrieve it fine now. 😸 

```bash
$ curl -I https://repo.gradle.org/artifactory/jcenter/gg/jte/jte-kotlin/2.0.3/jte-kotlin-2.0.3.jar
HTTP/1.1 200 OK
Date: Sat, 14 May 2022 10:32:46 GMT
Content-Type: application/java-archive
Content-Length: 17757
```

**Comment by casid** [comment]
Thanks, glad it's working now!

My guess is, that it just took some time for the maven central dependency to appear in the gradle artifactory cache.
