### ISSUE TITLE
Using UtfByte output

### ISSUE THREAD

**Issue by sJakovac** [casid/jte#158]
If the model for  template generates data dynamically, is it all stored in buffer of `Utf8ByteOutput` before passing it to actual output stream(`utf8byteOutput.writeTo(actualOutput)`) or is it passed on the fly while data is being generated by `templetEnigne.render(template, model, utf8byteOutput)`

Example:
- "model":
```java
package my.pack;

import java.util.Iterator;

public class IntGenerator implements Iterable<Integer> {

    private final int from;
    private final int to;

    public IntGenerator(int from, int to) {
        this.from = from;
        this.to = to;
    }

    @Override
    public Iterator<Integer> iterator() {
        return new IntIterator();
    }

    private class IntIterator implements Iterator<Integer> {

        private int current = from;

        @Override
        public boolean hasNext() {
            return current < to;
        }

        @Override
        public Integer next() {
            return current++;
        }
    }
}
```

- template `demo.jte` precompiled with maven parameter `<binaryStaticContent>true</binaryStaticContent>`:
```
@import my.pack.IntGenerator
@param IntGenerator model

@for(Integer value : model)
    My value: ${value}
@endfor
```
- demo:
```java
package my.pack;

import gg.jte.ContentType;
import gg.jte.TemplateEngine;
import gg.jte.output.Utf8ByteOutput;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;

public class Demo {
    private static final TemplateEngine TEMPLATE_ENGINE = TemplateEngine.createPrecompiled(ContentType.Plain);

    public static void main(String[] args) {
        var model = new IntGenerator(0, 10_000_000);
        var templateOutput = new Utf8ByteOutput();
        try (OutputStream os = Files.newOutputStream(Path.of("demo.txt"))) {
            // see below comment/question
            TEMPLATE_ENGINE.render("demo.jte", model, templateOutput);
            templateOutput.writeTo(os);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

Also, I find it strange that [docs](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#binary-rendering-for-max-throughput) show calling `templateEngine.render(...)` before `templateOutput.writeTo(...)`. That makes me guess that rendering template does actualy create and store all data from model in this case.

**Comment by casid** [comment]
Yes, the `Utf8ByteOutput` collects all output and writes everything in one go to the underlying stream. Usually this performs really well, as most output comes from the static template parts and `Utf8ByteOutput` just collects those references. Also, this implies that the user never sees incomplete markup (e.g. when an exception during rendering occurs) and it is very cheap to provide the HTTP repsonse with a content-length.

However, it would absolutely make sense to provide another template output, that directly streams to the underlying `OutputStream`. Would you be interested in contributing such a template output, e.g. `Utf8ByteStreamingOutput`?

**Comment by sJakovac** [comment]
I'll definitely consider contributing. Probably not in the next few weeks tho.

In the meantime, does `FileOutput` also collect data before passing it to the output file? I've realized that I've prematurely optimized and that I have much more dynamic data so `Uft8ByteOutput` and static binary data aren't that advantageous.

**Comment by casid** [comment]
Thanks! Yes, for very dynamic data written to files, `FileOutput` is the optimal template output to use.
