### ISSUE TITLE
2.0.3 NullPointerException for maven plugin

### ISSUE THREAD

**Issue by Akromangel** [casid/jte#159]
[ERROR] Failed to execute goal gg.jte:jte-maven-plugin:2.0.3:precompile (default) on project ppdh-integration-tests: Execution default of goal gg.jte:jte-maven-plugin:2.0.3:precompile failed.: NullPointerException -> [Help 1]

Configuration for plugin:
```xml
            <plugin>
                <groupId>gg.jte</groupId>
                <artifactId>jte-maven-plugin</artifactId>
                <version>${jte.version}</version>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/test/resources/templates</sourceDirectory>
                    <packageName>${package-name}</packageName>
                    <contentType>Plain</contentType>
                </configuration>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>precompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
According to documentation parameter `targetDirectory` has [default value](https://github.com/casid/jte/blob/7eea836c805f4b2339132d8d41fd2b599499edbb/jte-maven-plugin/src/main/java/gg/jte/maven/GeneratorMojo.java#L33) but in my case I have NPE.

When I add some `targetDirectory` then there is no error but classes are generated in a wrong place (this is another issue).

Small stack trace
```text
Caused by: java.lang.NullPointerException
    at sun.nio.fs.UnixPath.normalizeAndCheck (UnixPath.java:77)
    at sun.nio.fs.UnixPath.<init> (UnixPath.java:71)
    at sun.nio.fs.UnixFileSystem.getPath (UnixFileSystem.java:281)
    at java.nio.file.Paths.get (Paths.java:84)
    at gg.jte.maven.CompilerMojo.execute (CompilerMojo.java:90)
```

```shell
shell 10:56:50 $ mvn --version
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /home/-/.sdkman/candidates/maven/current
Java version: 1.8.0_332, vendor: Azul Systems, Inc., runtime: /home/-/.sdkman/candidates/java/8.0.332-zulu/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-33-generic", arch: "amd64", family: "unix"
```
OS is Ubuntu 22.04 if it matters.

**Comment by casid** [comment]
Thanks for reporting! You're using the `CompilerMojo` which currently has no [no default value](https://github.com/casid/jte/blob/7eea836c805f4b2339132d8d41fd2b599499edbb/jte-maven-plugin/src/main/java/gg/jte/maven/CompilerMojo.java#L41) for `targetDirectory`. The NPE here is extremely unhelpful. My suggestion would be to either mark the parameter as `required` or to set a default value like `jte-classes`.

I checked `packageName` and noticed that it is annotated with `@Parameter(readonly = true)`, which seems wrong to me. I'll try to reproduce with your specified maven version.

**Comment by casid** [comment]
I changed the targetDirectory parameter to `required`, so the npe won't happen.

I'm closing this issue, still investigating the `packageName` issue in #152.
