### ISSUE TITLE
Gradle plugin feature request

### ISSUE THREAD

**Issue by mtdowling** [casid/jte#16]
This project looks great! I just wanted to submit a feature request for a Gradle plugin.

**Comment by casid** [comment]
Hey @mtdowling, thanks for the heads up! I'm not very experienced with gradle (except for Android development). Would you be interested in helping with a Gradle plugin?

**Comment by casid** [comment]
I just had a quick look how this could be done. I think it would be great if we could add the gradle plugin as a module to this repository and build it together with the rest of jte. This way we can make sure that the gradle plugin is always up-to-date and works with the current jte version.

I'd suggest to put it into a `jte-gradle-plugin` module. The main build runs with maven though. It looks like the Spring Boot team faced the same problem and was able to build their gradle plugin from maven.

[This stackoverflow post](https://stackoverflow.com/questions/27555560/how-can-i-build-a-gradle-plugin-with-maven) looks like a good starting point I guess.

**Comment by Jerbell** [comment]
This is not a proper solution, but as an interim measure you can use a `JavaExec` task rather than a proper Gradle task or plugin.  This uses Shadow Jar Gradle plugin and Kotlin, but could be adjusted to work with Java.

In `build.gradle.kts`:
```kotlin
val precompileJteTemplates = tasks.register<JavaExec>("precompileJteTemplates") {
    description = "Precompile all JTE templates files."
    group = "build"
    main = "com.flowcrypt.utils.JteTemplatePrecompiler"
    val mainSourceSet = project.the<SourceSetContainer>()["main"]
    classpath = mainSourceSet.compileClasspath.plus(mainSourceSet.output)
    shouldRunAfter("compileKotlin")
    outputs.upToDateWhen { false } // not sure if this is necessary
}

tasks.named("shadowJar") {
    dependsOn(precompileJteTemplates)
}
```

And the class itself (uses Kotlin logging):
```kotlin
package com.flowcrypt.utils

import gg.jte.ContentType
import gg.jte.TemplateEngine
import gg.jte.resolve.DirectoryCodeResolver
import mu.KotlinLogging
import java.nio.file.Path
import java.util.concurrent.TimeUnit

object JteTemplatePrecompiler {

    private val logger = KotlinLogging.logger {}

    // these ideally shouldn't be hard coded
    private val sourceDirectory: String = "src/main/jte"
    private val targetDirectory: String = "build/resources/main"
    private val compilePath: List<String> = emptyList() // redundant
    private val contentType: String = "Html"

    @JvmStatic
    fun main(args: Array<String>) {

        val start = System.nanoTime()

        val source: Path = Path.of(sourceDirectory)
        val target: Path = Path.of(targetDirectory)

        logger.info("Precompiling jte templates found in $source")

        val templateEngine: TemplateEngine = TemplateEngine.create(DirectoryCodeResolver(source), target, ContentType.valueOf(contentType))

        val amount: Int
        amount = try {
            templateEngine.cleanAll()
            templateEngine.precompileAll(compilePath)
        } catch (ex: java.lang.Exception) {
            logger.error("Failed to precompile templates.", ex)
            throw ex
        }

        val end = System.nanoTime()
        val duration = TimeUnit.NANOSECONDS.toSeconds(end - start)
        logger.info("Successfully precompiled " + amount + " jte file" + (if (amount == 1) "" else "s") + " in " + duration + "s to " + target)
    }
}
```

Ideally this should be a Gradle Task/Plugin but I had problems with the classpath & didn't have the time.

**Comment by casid** [comment]
Thanks for sharing! That looks very straight forward.

**Comment by pa-dieter** [comment]
We will definitely check it out.

**Comment by casid** [comment]
@iRebbok was to kind to contribute a gradle plugin! It can do the same as the maven plugin :-)

It's already available at the gradle plugin repository: https://plugins.gradle.org/plugin/gg.jte.gradle

Documentation is up-to-date, feel free to give it a try 👍 
https://github.com/casid/jte/blob/master/DOCUMENTATION.md#precompiling-templates
