### ISSUE TITLE
Question: th:replace with jte

### ISSUE THREAD

**Issue by simonmonecke1708** [casid/jte#162]
Hi,

I am currently rewriting our existing Thymeleaf template to try jte out. In these we use th:replace to include static HTML snippets in various templates. Unfortunately, I can't convert these snippets to jte templates as they are generated by other tools.

Is there a way with jte to include HTML files as I did before with th:replace?

Best regards,
  SImon

**Comment by casid** [comment]
Welcome @simonmonecke1708!

Currently this is only possible at runtime, meaning those static snippets need to be deployed to where jte is running. For example:

```java
package org.example;

import gg.jte.Content;

public class JteImport {
    public static Content importFile(String name) {
        return output -> output.writeContent(lookupFileContent(name));
    }

    private String lookupFileContent(String name) {
         // load file, maybe combined with some ConcurrentMap::computeIfAbsent
    }
}
```

From jte template:

```html
@import static org.example.JteImport.*;

<div>
    <p>Here comes a static HTML snippet:</p>

    ${importFile("test/snippet.htm")}
</div>
```

**Comment by simonmonecke1708** [comment]
The solution looks quite good. I will test this and rewrite more templates.

Thanks a lot and good luck with the project! Writing the templates feels very good so far

**Comment by casid** [comment]
Thank you for the heads up, that's great to hear :-)
