### ISSUE TITLE
Allowing html tags but not scripts

### ISSUE THREAD

**Issue by NeedNot** [casid/jte#167]
I was wondering how I could allow HTML tags while still blocking scripts when using the $unsafe{} or without it I guess if that's needed

**Comment by casid** [comment]
Welcome @NeedNot!

Can you tell me a bit more about your usecase? Where are the HTML Tags coming from? Are they user input, or trusted?

All I can tell is that `$unsafe` is dangerous and should be avoided.

**Comment by NeedNot** [comment]
> Welcome @NeedNot!
> 
> Can you tell me a bit more about your usecase? Where are the HTML Tags coming from? Are they user input, or trusted?
> 
> All I can tell is that `$unsafe` is dangerous and should be avoided.

yes so it's user generated. it's use case is most like a forum

**Comment by kelunik** [comment]
You can use jsoup to clean the HTML and only keep a list of tags and attributes you want to allow.

**Comment by NeedNot** [comment]
ok i worded this wrong. i have since been looking into this what I need is to escape with select tags.
ik how do purge bad tags but I need to escape or replace the <> with the entities on select tags

**Comment by casid** [comment]
Nice!

In case you want to avoid `$unsafe` in templates, you can also provide some sort of helper method to your jte view model.

```java
public gg.jte.Content getForumContent() {
    String cleaned = Jsoup.clean(userForumContent);
    return o -> o.writeContent(cleaned); // This writes unescaped to the template output
}
```

And use it in the template like this:

```html
@param ForumViewModel vm

<div>
   ${vm.getForumContent()}
</div>
```
