### ISSUE TITLE
ktor integration - models allowed?

### ISSUE THREAD

**Issue by 2x2xplz** [casid/jte#168]
Hi, trying to use jte with ktor (https://ktor.io/docs/jte.html) however the example and the `JteContent` function appears to only accept a map of params, rather than any models or objects.

The example code is 
```
get("/index") {
    // ktor example (no model, just a map of params)
      val params = mapOf("id" to 1, "name" to "John")
      call.respond(JteContent("index.kte", params))
    // my attempt, using a model - type mismatch
      call.respond(JteContent("test.kte", MyModel(id = 1, name = "John")))
}

// my attempt requires a data class (but fails anyway)
data class MyModel(val id: Int, val name: String)
```
This would seem to limit compatibility with jte templates that expect models, plus make creating new templates more tedious. Am I missing a way to use models with Ktor and jte or is it limited to Maps/Params? Thanks!

**Comment by casid** [comment]
Hi @2x2xplz, using one model class for a template is the recommended way for jte/kte templates. Especially with the IntelliJ plugin this is very productive, cause you see in the template what's available in the model.

The template looks different, though.

With one model parameter:
```
@param model: MyModel

<%-- You have nice autocomplete through the IntelliJ plugin here --%>
Hello ${model.name}, your id is ${model.id}.
```

With parameter map:
```
<%-- You don't have autocomplete through the IntelliJ plugin here --%>
@param id: Int
@param name: String

Hello ${name}, your id is ${id}.
```

**Comment by 2x2xplz** [comment]
Thank you for the quick reply. Yes, I want to use the first example, the problem is the ktor plugin is forcing me to use the second example.

`call.respond(JteContent("test.kte", MyModel(id = 1, name = "John")))`  <--- type mismatch
`call.respond(JteContent("test.kte", mapOf("id" to 1, "name" to "John")))` <--- compiles and works (requires 2 params in template)

I also tried wrapping the object inside a Map with its parameter name:
`call.respond(JteContent("testing.kte", mapOf("mod" to MyModel(1, "John"))))`
This compiles, however when you visit the page, you get the error `Classifier 'MyModel' does not have a companion object, and thus must be initialized here`

template:
```
@import webapi.MyModel
@param mod : MyModel
Hello world, my name is ${mod.name} and my id = ${mod.id}
```


this is JtetestingGenerated for the last example, line 17 (val mod = ... ) is the source of the companion object error:
```
package gg.jte.generated.ondemand
import webapi.MyModel
class JtetestingGenerated {
companion object {
	@JvmField val JTE_NAME = "testing.kte"
	@JvmField val JTE_LINE_INFO = intArrayOf(0,0,2,2,2,2,5,5,5,5,5,5,5,6)
	@JvmStatic fun render(jteOutput:gg.jte.html.HtmlTemplateOutput, jteHtmlInterceptor:gg.jte.html.HtmlInterceptor?, mod::) {
		jteOutput.writeContent("\r\n\r\nHello world, my name is ")
		jteOutput.setContext("html", null)
		jteOutput.writeUserContent(mod.name)
		jteOutput.writeContent(" and my id = ")
		jteOutput.setContext("html", null)
		jteOutput.writeUserContent(mod.id)
		jteOutput.writeContent("\r\n")
	}
	@JvmStatic fun renderMap(jteOutput:gg.jte.html.HtmlTemplateOutput, jteHtmlInterceptor:gg.jte.html.HtmlInterceptor?, params:Map<String, Any?>) {
		val mod = params["mod"] as :? ?: MyModel
		render(jteOutput, jteHtmlInterceptor, mod);
	}
}
}
```

**Comment by casid** [comment]
Thanks for the additional info. I just wrote a test case for this and with the current jte version it seems to work (https://github.com/casid/jte/commit/af404981ecbd4fe1f86723bbce4600469f75d9a8).

My generated class looks different to the one you posted. Can you override the jte version used by ktor to the latest release, so that we can check if this is the problem?

```kotlin
package gg.jte.generated.precompiled
class JtehelloDataClassGenerated {
companion object {
	@JvmField val JTE_NAME = "helloDataClass.kte"
	@JvmField val JTE_LINE_INFO = intArrayOf(0,0,0,0,0,1,1,1,1,1,1,1,1)
	@JvmStatic fun render(jteOutput:gg.jte.html.HtmlTemplateOutput, jteHtmlInterceptor:gg.jte.html.HtmlInterceptor?, model:test.DataClass) {
		jteOutput.writeContent("Hello ")
		jteOutput.setContext("html", null)
		jteOutput.writeUserContent(model.name)
		jteOutput.writeContent(", your id is ")
		jteOutput.setContext("html", null)
		jteOutput.writeUserContent(model.id)
		jteOutput.writeContent(".")
	}
	@JvmStatic fun renderMap(jteOutput:gg.jte.html.HtmlTemplateOutput, jteHtmlInterceptor:gg.jte.html.HtmlInterceptor?, params:Map<String, Any?>) {
		val model = params["model"] as test.DataClass
		render(jteOutput, jteHtmlInterceptor, model);
	}
}
}
```

**Comment by casid** [comment]
Oh, I could reproduce your issue:

This does not compile:

```
@param model : test.DataClass
Hello ${model.name}, your id is ${model.id}.
```

This does compile:

```
@param model: test.DataClass
Hello ${model.name}, your id is ${model.id}.
```

As a workaround, could you try removing the space after the `mod` variable name in your template?

I will try to provide a fix this evening after work.

**Comment by casid** [comment]
Couldn't resist to have a quick look. This should be fixed now.

**Comment by 2x2xplz** [comment]
Again, thank you for the quick replies. You were right that just removing the extra space in the `@param` declaration made the difference. I am now able to use the ktor plugin with a data class / model. Terrific!

```kotlin
package webapi

...imports...

data class MyModel(val id : Int, val name: String)

fun main() {
    // ktor startup
    embeddedServer(Netty, port = 8080, watchPaths = listOf("resources", "classes")) {
        install(Jte) {
            val resolver = DirectoryCodeResolver(Path.of(config.webconfig.jteTemplateFolder))
            templateEngine = TemplateEngine.create(resolver, gg.jte.ContentType.Html)
        }
        basicRoutes()
    }.start(wait = true)
}

fun Application.basicRoutes() {
    routing {
        get("/testing") {
            call.respond(JteContent("testing.kte", mapOf("mod" to MyModel(15, "Jimmy"))))
        }
    }
}
```

testing.kte - `mod: MyModel` works! but `mod : MyModel` does not. watch for the extra spaces!
```
@import webapi.MyModel

@param mod: MyModel

Hello world, my initial is ${mod.name.first()}. and my id = ${mod.id}
<p>
${when {
    mod.id > 100 -> "I was hired late"
    mod.id > 10 -> "I was an early hire"
    mod.id > 1 -> "I was friends with the founder"
    mod.id == 1 -> "I founded this company!"
    else -> "My id isn't even real"
}}
</p>
```

**Comment by casid** [comment]
Oh, I'm not sure how ktor's development mode is implemented, but my guess would be that they use a custom ClassLoader for this. There's been a similiar issue with spring boot, so that might be a good starting point: https://github.com/casid/jte/issues/70#issuecomment-798949558

**Comment by casid** [comment]
I just released version [2.1.2](https://github.com/casid/jte/releases/tag/2.1.2) to maven central, including this fix :-)

**Comment by 2x2xplz** [comment]
> Oh, I'm not sure how ktor's development mode is implemented, but my guess would be that they use a custom ClassLoader for this. There's been a similiar issue with spring boot, so that might be a good starting point: [#70 (comment)](https://github.com/casid/jte/issues/70#issuecomment-798949558)

Just to be clear, this is not a bug or a problem with jte. Just wanted to document the fix in case someone has the same issue and does a search for ClassCastException or something similar.

**Comment by casid** [comment]
Kind of, it probably might still be convenient to use the development mode for hot reload of Kotlin classes.

I haven't got the chance to work with ktor yet, so that would be an opportunity to look into it :-)

**Comment by casid** [comment]
I did setup a little ktor project and was able to reproduce the class loader problem.

During initialization the current threads context class loader is the application class loader. This is what jte uses as parent class loader for templates.

```kotlin
install(Jte) {
    val resolver = DirectoryCodeResolver(Path.of("src/main/kte"))
    templateEngine = TemplateEngine.create(resolver, gg.jte.ContentType.Html)
}
```

During rendering, the class loader is io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader. This leads to the ClassCastException.

Unfortunately I'm not very experienced in Kotlin / ktor development and the only fix I can think of would require some changes to the ktor jte plugin:
- The user passes a lambda to the plugin configuration that can be called to create a TemplateEngine instance
- The plugin checks if it is running in development mode or not
- In development mode, it checks if the classloader of the current template engine is still equal to the classloader of the current thread. If not, it recreates the TemplateEngine using the factory method before rendering.

**Comment by 2x2xplz** [comment]
Just wanted to follow up, the ClassCastException is not exclusive to jte, it appears to be a problem for other plugins also while in ktor development mode. See [this YouTrack ticket](https://youtrack.jetbrains.com/issue/KTOR-4729/ClassCastException-when-retrieving-plugins-in-testApplication). Also [here](https://youtrack.jetbrains.com/issue/KTOR-4164/Development-mode-class-loader-leads-to-ClassCastException-within-a-CouroutineScope).
