### ISSUE TITLE
< and > are not escaped in the HTML tag body

### ISSUE THREAD

**Issue by IvanPizhenko** [casid/jte#171]
JTE version: `gg.jte:jte-kotlin:2.1.2`

In the KTE page we have following code:
```kte
          @for (uid in ForSupport.of(existingUserIds))
            <div data-test="user-id-before-${uid.index}">${uid.get()}</div>
          @endfor
```
where `existingUserIds` is `Array<String>` containing 2 elements like this:
```kotlin
  val existingUserIds = arrayOf("<user@example.com>", "first@mock.test")
```

And here's piece of screenshot with HTML code that this has produced:
![image](https://user-images.githubusercontent.com/11859904/183308783-fbf0c932-de91-46a7-9ca6-eefa5f733600.png)
where you can see, that `<` and `>` were not escaped.

We create template engine as follows:
```kotlin
  TemplateEngine.createPrecompiled(ContentType.Html)
```
so according to [JTE HTML escaping documentation](https://github.com/casid/jte/blob/main/DOCUMENTATION.md#html-escaping) we would expect that this should have been escaped.

Is it a bug in JTE or we are doing something wrong.

**Comment by kelunik** [comment]
According to the highlighting in the inspector it's probably properly escaped, otherwise it should be highlighted in purple instead of being black text. I guess the inspector shows the decoded entities here, so try a right-click and choose `Edit as HTML` to see the actual source.

**Comment by IvanPizhenko** [comment]
Yes, really, `View Source` shows they are escaped properly:
![image](https://user-images.githubusercontent.com/11859904/183310689-a0585e7d-1b5d-4fd1-881d-8d17a73159c9.png)

**Comment by IvanPizhenko** [comment]
@kelunik Thank you for suggestion!
