### ISSUE TITLE
Includes of other template files ignored when compiling templates

### ISSUE THREAD

**Issue by bluelu** [casid/jte#172]
Hi,

In my templates, I have included another template file with all the css code (there is no parameter to pass) in order not to duplicate the code:

`@template.css()`

Rendering works fine in non compiled mode.

However compiling all the template files does not include the include and ads it as plain text in the java file.
When I decompile the compiled class file, I see that the template include is also included as plain text

`var0.writeContent("</title>\n\n@template.css()\n\n\nBuilt at:\n<b>");`

Any idea why this is happening? Thanks

Configuration to compile:
`
      <plugin>
        <groupId>gg.jte</groupId>
        <artifactId>jte-maven-plugin</artifactId>
        <version>1.12.1</version>
        <configuration>
          <sourceDirectory>${basedir}/src/main/jte</sourceDirectory>
          <targetDirectory>${basedir}/jte-classes</targetDirectory>
          <contentType>Html</contentType>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>precompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
`

Includes:
`
    <dependency>
      <groupId>gg.jte</groupId>
      <artifactId>jte</artifactId>
      <version>2.1.2</version>
    </dependency>
`

**Comment by casid** [comment]
Welcome @bluelu :-)

The syntax of including templates has been changed in jte 2. Your jte maven plugin is still on jte 1 and does not know about the new syntax yet.

Changing the jte-maven-plugin version to 2.1.2 should fix this.

You could set a property in your pom to ensure both plugin and dependency are always the same version, like this:


```xml
<properties>
   <jte.version>2.1.2</jte.version>
</properties>

...

<dependency>
    <groupId>gg.jte</groupId>
    <artifactId>jte</artifactId>
    <version>${jte.version}</version>
</dependency>

...

<plugin>
    <groupId>gg.jte</groupId>
    <artifactId>jte-maven-plugin</artifactId>
    <version>${jte.version}</version>
    <configuration>

... 

```

**Comment by bluelu** [comment]
Thanks for the quick help.

clearly my mistake and I should have noticed :-/

**Comment by casid** [comment]
No worries, glad I could help!
