### ISSUE TITLE
Using !{}-blocks adds extra semicola (empty statements); prevents break and continue from working

### ISSUE THREAD

**Issue by a-leithner** [casid/jte#174]
I recently started using JTE (great solution, btw) and while experimenting with loops, it struck me that there is no obvious way to prematurely exit a loop, so I resorted to using `!{break;}`. However, this generated `break;;`, which makes the compiler complain that the empty statement followed by the `break;` is unreachable.

I see two possible solutions to this problem:

  1. Make the compiler (precompiler, really?) remove the erroneous semicolon after single-keyword statements such as `break;` and `continue;` which has shown the same behaviour in my (very shallow) research, so that code like this would compile correctly:
     ```jte
     @for (int i = 0; i < 100; i++)
         @if (i  % 2 == 0) !{continue;} @endif
         ${i}
     @endfor
     ```
      Please note that I have not yet tracked down where the empty statement gets generated and I sadly currently do not have the resources for that.
  2. Add new `@`-keywords for such operations (e.g., `@break`, `@continue`), which would allow such exit statements to blend in nicely into the rest of the JTE control structures, for example:
     ```jte
     @for (int i = 0; i < 100; i++)
         @if (i  % 2 == 0) @continue @endif
         ${i}
     @endfor
     ```

Interestingly enough, specifying a loop label using `!{label:} @for (/* stuff */)` and then using `!{continue label;}` triggers the same unreachable statement error.

Doing some research, I noticed that the extra semicola get generated for every instruction inside `!{}`-blocks, even for aforementioned loop labels, which obviously causes trouble. Removing the semicola at the end of such instructions inside JTE code makes the IntelliJ plugin complain that a "`;` was expected" but otherwise lets the template render correctly.

However, using labels as stated above won't even work if removing the semicolon from the `break` or `continue` instruction because the label applies to an empty statement always, which makes the label undefined and thus invalid to use with `break` or `continue`; also, it wouldn't even correctly apply to loops.

Given that even the documentation shows that `!{}`-blocks should be closed with a semicolon (which simply feels right, this is plain Java after all), it is an annoyance that there is a mismatch between the IntelliJ plugin (reporting errors) and the compiler (correctly but naively "fixing" the statement).

Could the fix be as simple as checking whether the statement string terminates with `;` and writing a semicolon otherwise to the generated Java source file? (Obviously, this wouldn't work for labels unless new labelling keywords are introduced into JTE, but some sacrifices have to be made, I guess.)

**Comment by casid** [comment]
Welcome @a-leithner!

Oh dear, that is a historic leftover from when we started with the creation of jte. Initially, it was planned to have `!{}` mostly for variable assignments and for that, it felt nicer to not having to type a semicolon.

However, when working on the IntlliJ plugin, it was necessary to include the semicolon there, otherwise some refactorings simply did not work. However, the code in jte itself was never updated to reflect this.

This is the line that would need to be adjusted: https://github.com/casid/jte/blob/389d138aa50c2231c7fe8e5041a6d20d6e61cbdc/jte/src/main/java/gg/jte/compiler/java/JavaCodeGenerator.java#L336

I think in most cases this will be safe to do, since the semicolon is specified in the documentation and also the IntelliJ plugin will complain if it is missing. My suggestion would be to remove it from the code generator and make a minor version bump, so that users won't be surprised by this change in a bugfix release.

**Comment by a-leithner** [comment]
Yep, that seems most reasonable! This would also enable loop labelling, right?

Thanks for fixing this so quickly – so far, JTE has been an absolute pleasure to work with.

**Comment by casid** [comment]
Thank you, that's great to hear!

And yes, that should enable loop labeling as well.

**Comment by casid** [comment]
I just released version 2.2.0 to maven central, in case you want to give it a try 👍

**Comment by a-leithner** [comment]
Can confirm that `break;` and `continue;` now work as expected. However, it should be probably documented somewhere that loop termination statements must be placed at the very end of the corresponding block, as any whitespace following them would in turn generate unreachable statements. But that's just a minor inconvenience and could probably be fixed by something like #10 in the future.

E.g., this won't work:
```
@for (int i = 0; i < 100; i++)
    @if (i % 2 == 0)
        !{continue;}
    @endif
    ${i}
@endfor
```
but this will:
```
@for (int i = 0; i < 100; i++)
    @if (i % 2 == 0) !{continue;}@endif <!-- NO space between } and @ -->
    ${i}
@endfor
```
(Just for reference here, in case anyone in the future stumbles upon this.)

I think this can be closed as done now.

**Comment by casid** [comment]
Thanks for giving it a try so quickly!

**Comment by kelunik** [comment]
@casid We should probably open another issue for the issue mentioned in https://github.com/casid/jte/issues/174#issuecomment-1253324260? The second variant isn't something I'd like to read.
