### ISSUE TITLE
Inherit whitespace when invoking tags?

### ISSUE THREAD

**Issue by mtdowling** [casid/jte#18]
Is there a way for the tag to inherit the whitespace indentation of the template that's calling it? Being able to call a tag relative to the current position in an outer template would be necessary for lots of use cases that need very specific control over whitespace (like code generators).

Given a template like this:

```
@import java.util.Map;
@import java.util.List;

@param String name
@param Map<String, List<String>> entries

Hello, ${name}

@for(Map.Entry<String, List<String>> entry : entries.entrySet())
    - ${entry.getKey()}:
      @tag.ShowEntry(values = entry.getValue())
@endfor
```

And a tag named ShowEntry.jte like this:

```
@import java.util.List;

@param List<String> values

@for(String value : values)
- ${value}
@endfor
```

The output is something like:

```
Hello, Person
    - a:
- foo
    - b:
- baz
- bar
```

I would need to be able to render output like:

```
Hello, Person
    - a:
      - foo
    - b:
      - baz
      - bar
```

**Comment by casid** [comment]
Hey @mtdowling, this isn't possible at the moment. Every template is precompiled independently from where it is called from. For rendering Html this isn't an issue, which is the primary use case of jte (for me). For Html, I'd love to add compile-time Html compression as a feature some day: https://github.com/casid/jte/issues/10

I added an experimental mode to trim the jte control structures from the output (`TemplateEngine#setTrimControlStructures`), that tries to remove extra indentations by jte control structures like `@if`, `@for` and so on. But that's still very experimental. And it doesn't solve the problem you describe.

May I ask what type of content you'd like to generate with jte?

**Comment by mtdowling** [comment]
My use case is code generation, so whitespace is super important for me. Thanks for clarifying.

**Comment by casid** [comment]
You're welcome. Yeah, I think for perfect control over whitespaces jte is not the right tool. I did some improvements to #10 over the weekend, but the moment you extract functionality in a tag the whitespaces will be different.

**Comment by edrd-f** [comment]
Was about to open an issue for the same reason as this one. Glad I didn't.

I see a lot of potential in JTE for general code generation, but some languages are very indentation-sensitive (e.g. YAML, Python and even Scala 3).

@casid when you said:

> Yeah, I think for perfect control over whitespaces jte is not the right tool.

You mean "at the current state but maybe in the future it will be" or "it's not intended for such use cases"? :grin: 

If you meant the former, we could discuss and I could help implement it (maybe even in a manner that also advances the implementation of https://github.com/casid/jte/issues/10).

**Comment by edrd-f** [comment]
I see. Thanks for the explanation!
