### ISSUE TITLE
mentioned at Devoxx

### ISSUE THREAD

**Issue by edward3h** [casid/jte#187]
[Graeme Rocher on Micronaut](https://youtu.be/3t-gwFuOtnM?t=5175) (Youtube) - mentioned JTE as his current favourite view library for Micronaut :)

**Comment by casid** [comment]
Wow, that‘s really cool, thanks for sharing.

„Compiles flawlessly to native“ - thanks to your great contributions on GraalVM nativei compilation @edward3h 🚀❤️

**Comment by casid** [comment]
@edward3h I'm closing this as informative, to keep the list of open issues short.
