### ISSUE TITLE
Booleans should not be coerced to false on null

### ISSUE THREAD

**Issue by kelunik** [casid/jte#19]
https://github.com/casid/jte/blob/23b16ae6af5eddafa641febbafced05a69231726/jte-runtime/src/main/java/gg/jte/internal/NullCheck.java#L20

This is just asking to result in some security vulnerability.

**Comment by casid** [comment]
This check is used for the experimental mode `TemplateEninge#setNullSafeTemplateCode`.

Any suggestion what to do instead of false?

**Comment by casid** [comment]
I just removed the feature `nullSafeTemplateCode` entirely. Besides the security implications it also comes with a heavy performance hit when running with `-XX:-OmitStackTraceInFastThrow`.
