### ISSUE TITLE
&nbsp;

### ISSUE THREAD

**Issue by 2x2xplz** [casid/jte#192]
Hi, I am trying to insert an HTML non-breaking space into a template, as the default when a certain parameter is otherwise empty:

`@param message: String = "&nbsp;"`

- My first attempt `${message}`, it was escaped and appeared as text in the HTML output.
- Next, I wrapped it with `$unsafe{message}` and that seemed to work, although I didn't really like using `unsafe` in this situation.
- However, when I ran this on a production server with compiled templates, `&nbsp;` was visible as text again in the output.

The output (Chrome DevTools) is identical:
dev (hot reloading)
![image](https://user-images.githubusercontent.com/16587079/212771015-d9462891-627e-484f-a8e5-0751d371dbdb.png)
prod (compiled)
![image](https://user-images.githubusercontent.com/16587079/212771036-18d8befe-3d0e-444d-ba64-94ec7e41e099.png)

but, as I mentioned, `&nbsp;` is invisible in the dev version and visible text in the production version.

Is there a better way to add a non-breaking space (or any HTML entity code)? Thanks!  (jte is fantastic, by the way)

**Comment by kelunik** [comment]
Yes, there is! You can use `String = null` with an `if` with an inline `&nbsp;`, or use a content block instead that defaults to a content block:

```
@param message: Content = @`&nbsp;`
```

**Comment by 2x2xplz** [comment]
Using standard (unquoted) `&nbsp;` in the body of the template, surrounded by `@if` and `@endif`, worked great, thank you!

FYI, another workaround (not relevant for all cases) is to set the non-breaking space in CSS via `content`, then just use jte to set (or not set) the class. Something like 
```css
.blankline::before {
  content: '\00A0' /* \00A0 is the CSS equivalent of &nbsp; */
}
```

If you use Tailwind for CSS, it can be a simple one-liner without external CSS:
`<div class="text-red-800 ${if (errorMessage.isBlank()) "before:content-['\\00A0']" else ""}">${errorMessage}</div>`

**Comment by 2x2xplz** [comment]
I'm going to revisit and update this answer 2 years later. The simplest option appears to be to forget encoding the character as `&nbsp;` but simply to copy-and-paste the non-breaking space Unicode character from a site like [Unicode Explorer](https://unicode-explorer.com/c/00A0) right into IntelliJ or VSCode. JTE will not change or escape these characters but they will be interpreted correctly in the browser. (JTE does escape `&` to `&amp;` in template variables, which is why using HTML entity codes don't work out of the box - `&nbsp;` becomes `&amp;nbsp;`)

<img width="584" alt="image" src="https://github.com/user-attachments/assets/f5fcc02a-5cb1-46a0-92f3-b3b104e74655" />

(x-text is an Alpine.js attribute)

This can typically be used for any HTML entity (such as those at [Toptal](https://www.toptal.com/designers/htmlarrows/symbols/)), however `&nbsp;` is more difficult than others because the nature of a whitespace character makes it more difficult to copy/paste than a visible character.
