### ISSUE TITLE
More documentation on how to start using .kte

### ISSUE THREAD

**Issue by rabacadabra** [casid/jte#196]
The documentation does mention that we can use Kotlin as expression language, and I can see traces of the "how-to"s in some PRs and some issues, but there doesn't seem to be any documentation on enabling kte. Can anyone list down the steps to to get it to work?

I followed these steps and somehow, the `kte` files aren't detected:
- Added dependency `gg.jte:jte-kotlin:2.2.4`
- Changed a template file extension to `.kte`

Getting an "Unresolved template" error in the IDE wherever the template is getting called, and at runtime, the following exception is thrown:
```
No parameter information for common/addHiddenFields.jte
	at gg.jte.compiler.java.JavaCodeGenerator.appendParams(JavaCodeGenerator.java:452)
	at gg.jte.compiler.java.JavaCodeGenerator.onTemplateCall(JavaCodeGenerator.java:391)
	at gg.jte.compiler.TemplateParser.lambda$doParse$3(TemplateParser.java:262)
```

I'm using Javalin + JTE, and these are the existing relevant config:
- Dependencies:
  - gg.jte:jte:2.2.4
  - io.javalin:javalin-rendering:5.2.0
- Plugin:
  - id("gg.jte.gradle") version("1.12.0")
- in JavalinConfig
  - `JavalinJte.init(TemplateEngine.create(ResourceCodeResolver("jte"), ContentType.Html))` (all templates, jte and kte, are in the jte folder itself)

**Comment by casid** [comment]
If I remember correctly, mixing jte / kte templates is not very well supported. What happens if you render a simple kte template without calling other jte templates?

I think it is unrelated to the problem you encounter, but `gg.jte.gradle` should be the same version as the jte dependency (2.2.4).

**Comment by rabacadabra** [comment]
alright, i'll check how it works without mixing jte and kte.

Otherwise, are the steps I mentioned above enough to enable kte files?

**Comment by casid** [comment]
Yes, other than adding the jte-kotlin dependency, there's nothing more to do.

**Comment by rabacadabra** [comment]
the issue was with mixing jte + kte. once i changed all the templates to kte, everything was resolving correctly.

Thanks @casid

**Comment by casid** [comment]
Thanks for confirming, glad it's working for you now.
