### ISSUE TITLE
passing value to javascript function 

### ISSUE THREAD

**Issue by highspeedlowdraghightechlowlife** [casid/jte#198]
is there a way to pass the a value e.g.    ${page.userName}    to a javascript script that's escaped in the @raw tag? document.getelementbyId doesn't seem to work because its a jtw file not an HTML.

**Comment by casid** [comment]
Welcome, @highspeedlowdraghightechlowlife!

One option would be to not use `@raw` for the javascript and use ${page.userName} within the script.

I don't know what jtw is, but it appears, that putting the info in a `data` attribute and accessing that from within the script doesn't work, right?

**Comment by casid** [comment]
Hope I could help, if you need further info, feel free to reopen.
