### ISSUE TITLE
setTrimControlStructures isn't working

### ISSUE THREAD

**Issue by rjma30** [casid/jte#199]
Hello, I'm using JTE in my spring boot app and I'm not sure why setTrimControlStructures isn't working. I have the following JTE config:
```
@Configuration
public class JteConfig {

  @Bean
  public TemplateEngine templateEngine() {
    var templateEngine = TemplateEngine.createPrecompiled(Plain);
    templateEngine.setTrimControlStructures(true);
    return templateEngine;
  }
}
```
If you need more details, please let me know.
Thank you!

**Comment by casid** [comment]
Welcome, @rjma30!

`trimControlStructures` has no effect when loading precompiled templates (since the trimming happens at compile time).

You probably need to remove the option here and set it when precompiling templates, probably through maven/gradle plugin.

**Comment by casid** [comment]
Oh, one more question, are you rendering HTML documents with jte? If so, I would recommend `ContentType.Html` instead of `ContentType.Plain`. Besides the added security, it also offers some convenience features: https://github.com/casid/jte/blob/main/DOCUMENTATION.md#html-rendering

**Comment by rjma30** [comment]
Hi @casid, It worked by setting it true via gradle! Thank you and apologies for my ignorance. Also, I'm not using html. I'm using jte for network device CLI configurations and it is perfectly doing its job :-)
