### ISSUE TITLE
Spring Devtools + jte causes ClassCastException

### ISSUE THREAD

**Issue by devxzero** [casid/jte#201]
I've created a simple Spring Boot application to test JTE, but it breaks when `spring-boot-devtools` is added as Gradle dependency and a jte `@for` loop is used over a simple pojo. (It works fine without the DevTools dependency.) The exception that is thrown is:
```
java.lang.ClassCastException: class example.Product cannot be cast to class example.Product (example.Product is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @39ab152b; example.Product is in unnamed module of loader 'app')
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
...
at gg.jte.generated.ondemand.example.JtepageGenerated.render(example/page.jte:24) ~[na:na]
```

The code under which the problem occurs:
```
@SpringBootApplication
public class JteExampleSpringbootApplication {
    public static void main(String[] args) {
        SpringApplication.run(JteExampleSpringbootApplication.class, args);

        CodeResolver codeResolver = new DirectoryCodeResolver(Path.of("src", "main", "jte"));
        TemplateEngine templateEngine = TemplateEngine.create(codeResolver, ContentType.Html);

        StringOutput output = new StringOutput();
        templateEngine.render("page.jte", generateProducts(), output);
    }

    private static List<Product> generateProducts() {
        return List.of("Car", "House", "Bike").stream().map(Product::new).collect(Collectors.toList());
    }
}
```

src/main/jte/page.jte:
```
@import example.Product

@param java.util.List<example.Product> products

<html>
    <body>
        <h1>Products</h1>
        
        <!-- This line is fine -->
        ${products.toString()}

        <ul>
            <!-- This line causes problems with DevTools + JTE -->
            @for(Product product : products)
                <li>Product...</li>
            @endfor
        </ul>
    </body>
</html>
```
(`Product` class is just a simple pojo.)

build.gradle:
```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.2'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'gg.jte.gradle' version '2.2.6'
}

group = 'example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    // Disabling the line below, removes the classCastException
    implementation 'org.springframework.boot:spring-boot-starter-web'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    implementation 'gg.jte:jte:2.2.6'
}
```

Full log and exception: [log.txt](https://github.com/casid/jte/files/10777347/log.txt)
Project code that causes the exception: [jteexample-springboot.zip](https://github.com/casid/jte/files/10777352/jteexample-springboot.zip)

**Comment by casid** [comment]
Welcome @devxzero, this is a classloader issue. I think spring devtools enable hot reload of by providing their own classloader. I did a quick test on your sample project and passed the Spring classloader as parent classloader to the template engine:

`TemplateEngine templateEngine = TemplateEngine.create(codeResolver,  Paths.get("jte-classes"), ContentType.Html, JteExampleSpringbootApplication.class.getClassLoader());`

After that change, the template is rendered successfully again.

**Comment by casid** [comment]
Also, thank you for the detailed report including a sample project, that's awesome! :-)

**Comment by devxzero** [comment]
Didn't expect the solution to be that easy and quick :D Thanks!

**Comment by boosh** [comment]
Glad this has been answered. It might be worth documenting it somewhere.
