### ISSUE TITLE
[Question] varargs and renderMap

### ISSUE THREAD

**Issue by edward3h** [casid/jte#211]
I noticed that the generated `renderMap` methods specifically exclude varargs parameters. What is the reason for that? I found it unexpected.

**Comment by casid** [comment]
Good question. I just never needed that feature before.

So you would need another overload `renderMap(Map<String, Object> params, Object... varargs)`?

**Comment by edward3h** [comment]
I was working on a generator for model classes and expected the varargs parameter to be part of the map. But I also understand that it's not really necessary, so I can avoid them. I'll share my project soon so it will make sense 😁

**Comment by casid** [comment]
That's cool, I'm excited to see what you created! I guess this is going to solve #131

**Comment by edward3h** [comment]
This is what I have now https://github.com/edward3h/jte-model-processor
It's not in a remotely finished state. I made an annotation processor so it's not directly dependent on jte. But I have an alternative idea where we put an "extension API" in jte that could hand over info on classes and params.
I'm happy with the design of interface that is being generated.
