### ISSUE TITLE
[Question] Support for a Spring Bean Component Approach?

### ISSUE THREAD

**Issue by tschuehly** [casid/jte#212]
Hello, I'm currently working on a Library called Spring ViewComponent.
https://github.com/tschuehly/spring-view-component/tree/multi-module

The Goal is to bring Component Like Structure known from Frontend Frameworks to Server Side Rendering.
I originally developed the Library only for Thymeleaf but I want to integrate different Template Engines. 
I wanted to integrate JTE next as I think the Syntax is quite nice.

I already created a working example with the spring boot starter: https://github.com/tschuehly/spring-view-component-jte-demo

One feature that makes the Library very useful is to nest components.
For Thymeleaf I created a custom attribute and attributeprocessor that enables me to replace this tag: 
`<div view:component="parameterViewComponent.render('Hello World')"></div>`

With the HTML the component renders:
https://github.com/tschuehly/spring-view-component/blob/467ee1d90c88a6d0e6f6ff3ee9c86db7185f5c9a/thymeleaf/src/main/kotlin/de/tschuehly/spring/viewcomponent/thymeleaf/ViewComponentProcessor.kt#L84

Now I was wondering if something like that would be possible with JTE.

I have seen that JTE tries to convert the ViewContext Object the nested component returns to a Content Type.
![image](https://user-images.githubusercontent.com/33346637/233793922-9f1a7814-ed8f-4094-b7d6-fa8f5a0fa040.png)

Is it possible for me to register a converter with the templateEngine so that it recursively renders this component with JTE and gives back this Content Type?

I would be happy to contribute, if you could get me a direction where I could start!
Kind Regards
Thomas

**Comment by casid** [comment]
Hmm, the jte idiomatic way would be to invoke the table component with `@template.table.TableViewComponent()`.

The other option would be, that the `render()` method of the TableViewComponent returns an object that implements `gg.jte.Content`.

**Comment by tschuehly** [comment]
Hey @casid thanks for the tip!

I got it working: https://github.com/tschuehly/spring-view-component/tree/master/examples/jte-demo
![jte-example](https://user-images.githubusercontent.com/33346637/233835445-eb98128e-747d-4d50-b152-fbfb9442b643.png)

The Developer Experience is very nice!

One further question: Is it possible to split the component into multiple files and reference them relative to the component? This usecase here applies for me aswell:
https://github.com/casid/jte/issues/213

I will present JTE as a part on my talk at the SpringIO Conference:
https://2023.springio.net/sessions/rapid-server-side-full-stack-web-development-with-thymeleaf-and-htmx/

**Comment by casid** [comment]
Thanks for the heads up and glad you got it working!

> Is it possible to split the component into multiple files and reference them relative to the component?

Splitting in multiple .jte files is possible. However, templates are always referenced absolute to the template root directory.

**Comment by tschuehly** [comment]
JTE is now supported as a Template Language for Spring ViewComponent: https://github.com/tschuehly/spring-view-component
