### ISSUE TITLE
I can't find the gradle plugin anywhere

### ISSUE THREAD

**Issue by MoreOwO** [casid/jte#217]
Gradle can't find gradle plugin and neither can i when searching by hand in the mavenCentral or in any other repos (except Xillio when searching with mvnrepository.com but even if it does exists there, i'm unable to access it)
Is it normal ? Is there a way to have the plugin regardless ?
Thanks

**Comment by edward3h** [comment]
It's in the Gradle Plugin Portal https://plugins.gradle.org/plugin/gg.jte.gradle . Are you using the syntax shown there to add it?

Do you have anything in `settings.gradle` that would change where plugins are resolved from?

**Comment by MoreOwO** [comment]
I do have something in my settings.gradle modifying where plugins are resolved from, but i included gradle.org, i guess something was wrong with gradle yesterday as it's fixed now
