### ISSUE TITLE
jte-maven-plugin runtime error

### ISSUE THREAD

**Issue by teverett** [casid/jte#222]
I have this configuration for `jte-maven-plugin` v 2.3.2.

`<sourceDirectory>src/main/jte</sourceDirectory>`

I am getting this exception:

<pre>
java.io.UncheckedIOException: Failed to resolve all templates in src/main/jte
...
Caused by: java.nio.file.NoSuchFileException: src/main/jte
...
</pre>

Could the problem be that I have directories inside src/main/jte?

**Comment by teverett** [comment]
Issue is resolved by

`<sourceDirectory>${basedir}/src/main/jte</sourceDirectory> `

**Comment by casid** [comment]
Glad it is working!
