### ISSUE TITLE
Allow arbitrary Charset for binary output

### ISSUE THREAD

**Issue by casid** [casid/jte#228]
Right now, only UTF-8 is supported. This would change the parameter in `gg.jte.gradle.JteTaskBase#setBinaryStaticContent` from `boolean` to a `Charset`.

This breaking change would likely be part of jte 3.0.

**Comment by kelunik** [comment]
I'd say let's keep things simple and stick to UTF-8.

**Comment by casid** [comment]
I think you are right. It could be a source of very nasty bugs if the encoding of the output and the encoding of the precompiled templates does not match.
