### ISSUE TITLE
Set Java 17 as new baseline

### ISSUE THREAD

**Issue by casid** [casid/jte#229]
By now, Java 8 and 11 are quite old and frameworks like Spring are moving to Java 17 as new baseline.

This brings a few improvements:
- We can use faster methods that aren't available on Java 8, for instance for File IO
- We can make use of `@Generated` annotation for jte classes (#208)
- Less energy and computing time needed for the CI pipeline
- We can use text blocks for our unit tests

It might be worth it to look into this commit 7fe0864f48de426c30b37fdeb858840327547c79 that introduced Java 8 support. There were a few places that had to use older and likely slower methods. By now, there are likely more places that can be improved.

This breaking change would likely be part of jte 3.0.

**Comment by edward3h** [comment]
"Big news" for my team at work was that AWS Lambda started direct support for 17 a few weeks ago.
