### ISSUE TITLE
JTE is slower than regular String.replace approach

### ISSUE THREAD

**Issue by doom369** [casid/jte#23]
Hello, first of all, thanks for the great library.

I made a simple benchmark in order to test JTE performance and seems JTE is much slower than regular `String.replace()` at least for simple use cases.

Benchmark:

```
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
@Fork(1)
@Warmup(iterations = 5, time = 1)
@Measurement(iterations = 5, time = 1)
public class JTETest {

    String primaryColor = "#ffffff";
    String templateTxt;
    CodeResolver codeResolver = new DirectoryCodeResolver(Path.of("xxx/templates"));
    TemplateEngine templateEngine = TemplateEngine.create(codeResolver, ContentType.Plain);


    @Setup
    public void setup() {
        templateTxt = "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + "${primaryColor}\n"
                + "</head>\n"
                + "</html>";

    }

    @Benchmark
    public String concat() {
        return "<!DOCTYPE html>\n"
                + "<html>\n"
                + "<head>\n"
                + primaryColor
                + "\n"
                + "</head>\n"
                + "</html>";
    }

    @Benchmark
    public String replace() {
        return templateTxt.replace("${primaryColor}", primaryColor);
    }

    @Benchmark
    public String templateEngine() {
        TemplateOutput output = new StringOutput();
        templateEngine.render("replace_test.jte", primaryColor, output);
        return output.toString();
    }

}
```

replace_test.jte:

```
@param String primaryColor

<!DOCTYPE html>
<html>
<head>
${primaryColor}
</head>
</html>

```
Result:

```
Benchmark               Mode  Cnt     Score     Error  Units
JTETest.concat          avgt    5    25.720 ±   2.108  ns/op
JTETest.replace         avgt    5    75.095 ±   8.815  ns/op
JTETest.templateEngine  avgt    5  2867.906 ± 183.810  ns/op
```

For the large template 1kb and many replacements, JTE is still slower ~30%. Is that expected?

In theory, if the template doesn't have any control flow, it could be compiled to String concat pattern:

"<head>" + primaryColor + "</head>", where `OptimizeStringConcat` kicks in. That should make it even faster than regular `String.replace` pattern. WDYT?

**Comment by jjlharrison** [comment]
What about output escaping? JTE isn’t just replacing the value, it’s detecting characters that need to be sanitized. A fairer benchmark would pass the input value through `StringEscapeUtils`.

**Comment by doom369** [comment]
@jjlharrison correct, `ContentType.Plain` is used, however, I did the test with escaping as well. It has no visible effect as there is nothing to escape.

**Comment by casid** [comment]
@doom369 thanks for reporting! I think this is because of the hot reload feature being active. Before each template rendering, jte checks if the template was modified and needs recompilation, in `gg.jte.TemplateEngine#resolveTemplate`:

```
private Template resolveTemplate(String name) {
    if (templateMode == TemplateMode.OnDemand && templateLoader.hasChanged(name)) {
        synchronized (templateCache) {
            if (templateLoader.hasChanged(name)) {
                Template template = templateLoader.load(name);
                templateCache.put(name, template);
                return template;
            }
        }
    }
    return templateCache.computeIfAbsent(name, templateLoader::load);
}
```

For usage in production env, `gg.jte.TemplateEngine#createPrecompiled` would run in `Mode.Precompiled` and eliminate this lookup.

For your benchmark you could try to subclass `gg.jte.resolve.DirectoryCodeResolver` and override `hasChanged` to something like this:

```
@Override
public boolean hasChanged(String name) {
    return false;
}
```

Let me know if this works :-)

**Comment by doom369** [comment]
@casid you're right, results are much better now, however still slower than I would expect :)

```
Benchmark               Mode  Cnt    Score   Error  Units
JTETest.concat          avgt    5   25.736 ± 2.861  ns/op
JTETest.replace         avgt    5   71.350 ± 0.992  ns/op
JTETest.templateEngine  avgt    5  584.666 ± 7.653  ns/op
```

**Comment by casid** [comment]
@doom369 I would guess you are also measuring the lookup of the template class, via `ConcurrentHashMap` inside the `TemplateEngine`. Did you try with a little larger page? I believe the differences would be less and less. Usually you have that lookup only once per page rendered.

**Comment by doom369** [comment]
@casid lookups are cheap ~10 ns on average, so most likely it's something else.

**Comment by casid** [comment]
@doom369 interesting! I don't believe the reflective method call in `Template` is so expensive either.. Maybe it is the allocation of the `StringOutput`? It defaults to an initial capacity of 8kb, which is a sane default for a small website but a lot for this benchmark. What happens if you try a `StringOutput(64)` or something in that range?

**Comment by doom369** [comment]
@casid yeap

```
Benchmark               Mode  Cnt   Score    Error  Units
JTETest.concat          avgt    5  26.386 ±  4.651  ns/op
JTETest.replace         avgt    5  78.270 ± 16.821  ns/op
JTETest.templateEngine  avgt    5  90.127 ± 12.873  ns/op
```

with `StringOutput(64)`. But it still slower than regular replace :).

Initially, I was just curious if it will be faster than replace (that we use in our project a lot). As I saw that the library compiles the code to the Java class. So I thought that **tag${param}/tag** is compiled to:

`new StringBuilder().append("tag").append(param).apend("/tag").toString()` - that is heavily optimized by the JVM.
However, looks like that not possible right now as long as you have to pass `TemplateOutput` inside the render method.

So what I'm saying is - if the template doesn't have control instructions **if/for** etc it could be compiled to more effective code that could be optimized by the JVM (concat test demonstrates that in the benchmark above)

**Comment by casid** [comment]
That's still very interesting! Do you know what optimizations Java does when using a plain `StringBuilder` versus an abstraction like `StringOutput`? I'm wondering if the JIT would be able to inline the virtual methods of the interface.

What you could try if you want to dig deeper: Make a copy of the generated Java class and call it directly from your benchmark. This way we would see how much time is lost by the template lookup and the method invocation :-)

And it would be possible to compare the `StringOutput` to a raw `StringBuilder` :-)

**Comment by doom369** [comment]
@casid for Java 8 and below it was **-XX:+OptimizeStringConcat**. Since Java 9 it's **StringConcatFactory**. Checkout this JEP  - http://openjdk.java.net/jeps/280 it has a lot of interesting info.

> I'm wondering if the JIT would be able to inline the virtual methods of the interface.

Inlining is possible, however, the resulting concatenation won't be optimized, because it should be chaining calls pattern `.append("tag").append(param)` otherwise JIT doesn't optimize it.
In the case of StringOutput the result will be:

```
sb.append();
sb.append();
```

those code patterns are not optimized.

**Comment by casid** [comment]
Very interesting read! 

Also: Owner, Aleksey Shipilev, Endorsed by Brian Goetz, that's pretty amazing :-)

I think I'll try to recreate you benchmark with just the plain Java template class to see how big the performance gain of using chained StringBuilder vs TemplateOutput would be.

**Comment by casid** [comment]
@doom369 I've added a [JMH benchmark](https://github.com/casid/jte/blob/dcc84539789cb9a0db5073d05de39f47b58db82d/jte-benchmark/src/main/java/gg/jte/TemplateOutputTest.java) that compares `TemplateOutput` to direct `StringBuilder` usage.

I compiled the existing benchmark templates [welcome.jte](https://github.com/casid/jte/blob/dcc84539789cb9a0db5073d05de39f47b58db82d/jte/src/test/resources/benchmark/welcome.jte) and [layout/page.jte](https://github.com/casid/jte/blob/dcc84539789cb9a0db5073d05de39f47b58db82d/jte/src/test/resources/benchmark/layout/page.jte) with `ContentType.Plain` and put the generated Java classes inside the benchmark.

There are two versions of each the page and the layout. The one suffixed with `_TemplateOutput` is how it was generated by jte. The one suffixed with `_StringBuilder` was modified to use a `StringBuilder` directly. Whenever possible I chained the `append` calls.

The benchmark shows no noticeable performance difference though (running on Windows, JDK 11, Intel i7-6700K).

I'm not that experienced in JMH benchmarks, maybe I did something wrong. Would be interesting, how it runs on your end.

```
# Run complete. Total time: 00:00:21

Benchmark                          Mode  Cnt    Score    Error  Units
TemplateOutputTest.stringBuilder   avgt    5  582,745 ± 10,048  ns/op
TemplateOutputTest.templateOutput  avgt    5  574,382 ±  6,156  ns/op
```

**Comment by doom369** [comment]
@casid test is correct. In order to see the difference **_StringBuilder** should be compiled to the:

`return new StringBuider().append().append().toString();`

If you change the code to:

```
StringBuilder sb = new StringBuider();
sb.append();
sb.append();
sb.toString();
```

It won't be optimized.
In other words, only full chaining patterns are optimized.

Optimizing templates with flow instructions like this:

```
            if (page.getDescription() != null) {
                jteOutput.append("    <meta name=\"description\" content=\"").append(page.getDescription()).append("\">\r\n");
            }
```

probably impossible.

However, the template from my example could be optimized, because it doesn't have any flow instructions.

**Comment by casid** [comment]
@doom369 thanks for clarifying. I believe most real world usages will have some control flow (at least calling into other templates), so that they would not benefit from such an optimization.

We'd also lose some flexibility, like writing directly into a stream, if memory consumption is a concern.

What do you think? Shall we close this issue?

**Comment by doom369** [comment]
@casid up to you. If you think it doesn't worth the efforts - please close the ticket. In our product, all templates are without control instructions :). So we'll stick with regular `String.replace` than.

**Comment by casid** [comment]
@doom369 will do that then! And I think it's a good choice if simple `String.replace` is all that is needed to not add an additional dependency.

Thanks for posting the benchmark and all the insights on `String` performance :-)
