### ISSUE TITLE
Executing the template compilation in Test Applications

### ISSUE THREAD

**Issue by tschuehly** [casid/jte#237]
I want to write Integration Tests for my Spring ViewComponent Library for JTE:
The problem is that the template files are not compiled when starting the Application from a the test package: 

https://github.com/tschuehly/spring-view-component/tree/jte-tests/jte/src/test/kotlin/de/tschuehly/spring/viewcomponent/jte/application

It works completely fine when using it as a Gradle dependency:
https://github.com/tschuehly/spring-view-component/tree/jte-tests/examples/jte-demo/src/main/kotlin/de/tschuehly/jteviewcomponentdemo

Maybe @atomfrede has an Idea what is happening?

Thanks for your work!

**Comment by atomfrede** [comment]
From the gut I would say the autoconfiguration is not applied because the required classes are not on the classpath (but the test classpath). But need to have a more detailed look lster

**Comment by tschuehly** [comment]
The AutoConfiguration is applied, the templateResolver with the correct Template Engine is available:
![image](https://github.com/casid/jte/assets/33346637/4a8cb13e-ef59-4aa1-853b-bd66e36e0747)
All the same beans are available:
![image](https://github.com/casid/jte/assets/33346637/6583c9f8-d858-43d6-8154-676581d41dc6)
I think the issue is that the compilation step of the templates is not triggered.

**Comment by tschuehly** [comment]
I think the Issue is the correct configuration of the gradle plugin.
I did not use it yet as for the development the spring-boot starter did suffice.
I'm trying to configure the build.gradle.kts for the demo project right now but get a class def not found.
https://github.com/tschuehly/spring-view-component/blob/5e457840362211a7aaed7f272a42abd3e2ff9578/examples/jte-demo/build.gradle.kts

![image](https://github.com/casid/jte/assets/33346637/8744b505-0c8d-4407-a55b-1fb79a9a42a9)

I think we should update the spring boot documentation for the correct setup with the JTE plugin

**Comment by atomfrede** [comment]
@tschuehly Did you solve the issue or have some new insights?

**Comment by tschuehly** [comment]
@atomfrede Sadly, I did not yet have time to work further on this. I will write here again when I find some time to debug this

**Comment by tschuehly** [comment]
> Are you at jcon next week? Maybe we find some time to work together on this.

Yes on the 20. and 21.06

**Comment by casid** [comment]
@tschuehly Did you find something out at jcon?

In general, using jte in unit tests works, almost all tests in the jte project do this. The `ClassNotFoundException` is usually a classloader problem, aka the `TemplateEngine` being initialized with the wrong ClassLoader.

I think there was a similiar issue here: https://github.com/casid/jte/issues/201

**Comment by tschuehly** [comment]
@casid 
Sadly we did not have the time to look at it together, but thanks for pointing me in a direction.

I will investigate it in a couple weeks when I'm back from my vacation.

**Comment by atomfrede** [comment]
Ah yes devtools and jte (but freemarker too) also had some issues in my current project.

**Comment by tschuehly** [comment]
@casid 
It is not an issue with the ClassLoader, it is the same RestartClassLoader as it is with the TestApplication.Class.ClassLoader
The issue with the ClassNotFound was another Issue that dissappeared with proper config.

@atomfrede 
I think the Issue is that the DirectoryCodeResolver/TemplateLoader is somehow not triggered property / the TemplateLoader is not working properly, with the AutoConfiguration.

@casid Where/when are the Templates compiled? In the TemplateLoader.load? I couldn't really figure out how it works.

**Comment by casid** [comment]
@tschuehly in `OnDemand` mode templates are compiled the first time they are rendered. Or, if changes have been detected to the template rendered. For Java compilation happens in `gg.jte.compiler.java.JavaClassCompiler`, for Kotlin in `gg.jte.compiler.kotlin.KotlinClassCompiler`.

**Comment by tschuehly** [comment]
It is not an Issue with the TestApplication: https://github.com/tschuehly/spring-view-component/tree/6fea424ece5a50837cce775c15b6f69887d392b3/examples/jte-demo

I think it might have to do with the fact that it is a multi-module gradle project.

**Comment by tschuehly** [comment]
OMG I found the issue :(

In a multi module project one needs to include the module name in the templateLocation path:
`gg.jte.templateLocation: jte/src/test/kotlin`

@atomfrede 
I wonder if we could somehow resolve the path somehow according to the module in the [AutoConfiguration](https://github.com/casid/jte/blob/main/jte-spring-boot-starter-3/src/main/java/gg/jte/springframework/boot/autoconfigure/JteAutoConfiguration.java)

![image](https://github.com/casid/jte/assets/33346637/6fdd06e2-b67f-4d6c-8968-0d39f4ea09b9)


I think in the [DirectoryCodeResolver](https://github.com/casid/jte/blob/main/jte/src/main/java/gg/jte/resolve/DirectoryCodeResolver.java#L30) in the NoSuchFileException should be a Debug Log with file.getAbsolutePath() to log where JTE was looking for the template in the file system.
@casid What do you think of this?

**Comment by casid** [comment]
Glad you found the problem!

So far, jte avoided logging, since it would require to pull in additional dependencies. I'm not sure if there's a logging bridge that would address all logging needs of Java projects that use jte.

**Comment by atomfrede** [comment]
Why not just use java util logging?

**Comment by casid** [comment]
You are probably right. I'm pretty sure my knowledge is a bit outdated here, but back in the days there were quite some discussions if libraries should rely on JUL or not, like [this one](https://stackoverflow.com/questions/11359187/why-not-use-java-util-logging). So my stance on this has always been to avoid the problem altogether :-D

I think I can get away with it this time again, since the render method is already throwing an exception in case the template to load cannot be found. @tschuehly I've adjusted the exception message, so that the user sees directly in the thrown `TemplateNotFoundException` which file was tried to be resolved: https://github.com/casid/jte/commit/56c69768d0dc6ec16c948a9c8145ca6b67225677

**Comment by tschuehly** [comment]
@casid 
Awesome!

@atomfrede 
I think we should close this Issue and create a new one to adjust the spring starter. What do you think?
