### ISSUE TITLE
Is there a concept of a servlet context path in JTE?

### ISSUE THREAD

**Issue by Jerbell** [casid/jte#238]
We use absolute urls in our app, but we have need ot a flexible base URL, which could also be considered a server context/mapping in old J2EE.
Does JTE have anything like that?
Like `href="/login"` in JTE becomes `href="/mycontext/login"` in HTML.

If not I'll use my brain and do something.

Thanks!

**Comment by casid** [comment]
Hi @Jerbell, no such a thing does not exist in jte.

**Comment by Jerbell** [comment]
No worries.  I have another solution anyway.  Thanks!
