### ISSUE TITLE
Linting of jte templates in build

### ISSUE THREAD

**Issue by schowave** [casid/jte#242]
I've been using JTE for quite some time now and am very pleased with the tool support and Kotlin integration. Great job, casid! However, in my project I have already encountered a few error cases regarding an HTML element, for example:

```
<p class="my-class" style="margin: 0";>This is a text</p>
```

the semicolon has shifted. This might still work on its own, but when embedded in a framework, it can cause problems. Is there any way, for example, to break the gradle/maven build for this?

**Comment by casid** [comment]
Thank you for the heads up!

In theory, yes. With `ContentType.Html`, jte is kind of lazily "parsing" the HTML parts of the template. It should be possible to throw an error in case an "invalid" character is found between tag attributes.

However, looking at the [spec](https://html.spec.whatwg.org/multipage/syntax.html#attributes-2) it seems attribute names like `;` are actually valid HTML?!

> Attributes have a name and a value. Attribute names must consist of one or more characters other than [controls](https://infra.spec.whatwg.org/#control), U+0020 SPACE, U+0022 ("), U+0027 ('), U+003E (>), U+002F (/), U+003D (=), and [noncharacters](https://infra.spec.whatwg.org/#noncharacter). In the HTML syntax, attribute names, even those for [foreign elements](https://html.spec.whatwg.org/multipage/syntax.html#foreign-elements), may be written with any mix of [ASCII lower](https://infra.spec.whatwg.org/#ascii-lower-alpha) and [ASCII upper alphas](https://infra.spec.whatwg.org/#ascii-upper-alpha).

**Comment by casid** [comment]
@schowave sorry for the late reply. I've added a new HTML policy that validates attribute names. For now, it just makes sure that no semicolon is contained. We can still extend this in the future, but for now I would start with the case you reported here.

**Comment by schowave** [comment]
Hello @casid, thank you very much for validating the attributes! This seems to be a special case, so it makes sense to only perform this HTML validation here.
