### ISSUE TITLE
[3.0.0] Suggestions for jte-models

### ISSUE THREAD

**Issue by chkl** [casid/jte#243]
Congratulations for the new 3.0.0 release!

I'm currently giving it a test run and especially the jte-models extensions looks like a great addition.

I have two small suggestions (which I'd be happy to open PRs for):

1. ensure that the generated method names are valid Java. (Currently the file name is taken in verbatim, turning e.g. `user-dashboard.jte` to `public JteModel user-dashboard(...)` ). 
2. add some kind of configuration option to only add methods for _some_ of the jte files. Not every little component needs its own method - imho.

**Comment by edward3h** [comment]
Yes, those are good ideas. I'd be happy for you to open PRs :)

**Comment by casid** [comment]
Wow, that was quick. Thank you for the heads up Christian - and thank you for the PRs!

**Comment by casid** [comment]
Pull requests are merged. Thanks everyone! Closing this issue now.

**Comment by chkl** [comment]
Thanks y'all!
