### ISSUE TITLE
Issue upgrading from jte 2.3.0 to 3.0.0

### ISSUE THREAD

**Issue by spinscale** [casid/jte#249]
Hey,

I've probably been misusing JTE to support header/footer structures like this

Example: `src/main/jte/tag/header.jte`

```html
<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
</head>
<body>
```

Example: `src/main/jte/tag/footer.jte`

```html
</body>
</html>
```

Then using header and footer in `src/main/jte/main.jte`

```html
@template.tag.header()

<main class="container">
    <div class="grid">
        <div><h1>Please Login First</h1></div>
    </div>
</main>

@template.tag.footer()
```

Precompiling these returns

```
gg.jte.TemplateException: Failed to compile tag/header.jte, error at line XYZ: Unclosed tag <body>.
```

I suppose there is another mechanism now to properly support this? Do I need to use the `gg.jte.Content` for this?

Thank you!

**Comment by casid** [comment]
Hi @spinscale, yes `Content` is the preferred way to do this.

I would do something like this:

Create tag/layout.jte

```
@import gg.jte.Content
@param Content content

<html>
<head>
// header stuff goes here
</head>

<body>
${content}
</body>
```

**Comment by spinscale** [comment]
Works! Not yet sure how much I Like to embed everything within backticks, probably only my own bias at work here :-)

Do you think some kind of `extends` makes sense to not to do that, like in [pug](https://pugjs.org/language/inheritance.html) or [django templating](https://docs.djangoproject.com/en/4.2/ref/templates/language/)

**Comment by casid** [comment]
Yeah, I got that backticks feedback a few times already. The idea back then was, kind of a `String`, but actually a template lambda... 

Syntax aside.. Personally I think layouts with content blocks are a lot more powerful and readable compared to template inheritance. It is quite composable and nothing prevents you from having multiple slots in a layout. For instance in your example:

```
@param Content header = null
@param Content body
@param Content footer = null

<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
   ${header}
</head>
<body>
    ${content}
    @if(footer != null)
         <footer>
             ${footer}
         <footer>
    @endif
</body>
</html>
```

**Comment by edward3h** [comment]
[jte-models](https://github.com/casid/jte/tree/main/jte-models) supports a different way to do this. Given `layout.jte` as above, and `main.jte` as

```
    <main class="container">
        <div class="grid">
            <div><h1>Please Login First</h1></div>
        </div>
    </main>
```
The generated Templates class will let you do
```
templates.layout(templates.main()).render(...)
```

**Comment by casid** [comment]
@edward3h haven't thought about that option! Had to scratch my head a bit, but yeah, that works, which really shows how powerful the models extension is 👍
