### ISSUE TITLE
is there a javascript inlining in jte such as thymeleaf got?

### ISSUE THREAD

**Issue by stella6767** [casid/jte#252]
i got question. 

it is my jte file. i pass post object as param

```
@param com.stella.free.dto.PostDetailDto post

<link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css"/>

<div class="w-3/6 mx-auto mb-2">

    <div
            class="sm:text-3xl md:text-3xl lg:text-3xl xl:text-4xl font-bold cursor-pointer">
        ${post.getTitle()}
    </div>


    <div class="font-light text-gray-600">
        <h1 class="font-bold text-gray-700 hover:underline">By ${post.getUsername()}</h1>
    </div>

</div>


<div id="viewer">


</div>


<%--<span onclick="showContent('${post.getContent()}')">Click me</span>--%>


<style>


    #viewer {
        width: 50%;
        margin: 0 auto;
    }

</style>

<script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>


<script>

    // console.log(${post.getContent()});   // of course not access 
    
   
    const viewer = toastui.Editor.factory({
        el: document.querySelector('#viewer'),
        viewer: true,
        //initialValue: ${post.getContent()}
    });


</script>


```
i understand pass jte parame to js function. but i want direlty access in script tag

i mean is there feature like js inlining in jte?
<script th:inline="javascript">
	
</script>

**Comment by kelunik** [comment]
What is that supposed to do?

**Comment by stella6767** [comment]
> What is that supposed to do?


in thymeleaf, i can access variable in script tag with [[$()]]
<script>
    let postContent = [[${post.content}]];
</script>

**Comment by casid** [comment]
Only short answer, since I‘m on vacation. No, jte does not support this.

There are dozens of json frameworks out there and usually a project uses one of them, depending on the project needs (Jackson/Gson/dsljson..). With a few lines of code and your favorite json framework you should be able to write a little helper method that takes an Object and produces a `gg.jte.Content` block.

However, you may want to somehow limit its usage, to ensure no sensitive data is leaked. For instance, if your Dtos all have a shared interface you could only accept that interface and not all Objects.

**Comment by casid** [comment]
@stella6767 haven't heard back, was this answer helpful for you?

**Comment by stella6767** [comment]
> @stella6767 haven't heard back, was this answer helpful for you?

I haven't found a suitable solution..

**Comment by casid** [comment]
What JSON framework are you using in your project?

**Comment by stella6767** [comment]
> What JSON framework are you using in your project?

i use springboot + JTE. so i use default json framework in springboot (jackson-objectmapper). 
i not totally understand your suggest. i just want access jte param in script tag.

**Comment by casid** [comment]
Ahm, is `post.getContent()` a `String`? I thought it was a complex object. If it is a `String` you can simply do this:

```html
<script>
   let postContent = '${post.getContent()}';
</script> 
```

**Comment by stella6767** [comment]
> Ahm, is `post.getContent()` a `String`? I thought it was a complex object. If it is a `String` you can simply do this:
> 
> ```
> <script>
>    let postContent = '${post.getContent()}';
> </script> 
> ```

thanks you so much! i used diffrent solution with js (using input type hidden and document.getElementById().innerHTML) 
it is so simple solution. i didnt know that is so simple. maybe i'm dumb lol

**Comment by casid** [comment]
Glad you got it working!
