### ISSUE TITLE
cache busting static resources

### ISSUE THREAD

**Issue by erbrecht** [casid/jte#253]
Spring Boot provides some cache busting strategies for static resources:

https://www.baeldung.com/cachable-static-assets-with-spring-mvc

Basically, additionally providing the static resource under a filename that includes the MD5 hash value of the file itself. Thymeleaf and JSP both provide mechanisms for accessing this file:

source

```html
<script type="text/javascript" src="<c:url value="/js/foo.js" />">
```

becomes

```html
<script type="text/javascript" src="/js/foo-46944c7e3a9bd20cc30fdc085cae46f2.js">
```

This works natively, just by using the `c:url` tag from the core tag library. Thymeleaf is similar:

source

```html
<script type="text/javascript" th:src="@{/js/foo.js}">
```

likewise becomes

```html
<script type="text/javascript" src="/js/foo-46944c7e3a9bd20cc30fdc085cae46f2.js">
```

I'm not sure of the implementation details. These other templates can't just blindly append the hash value to every static resource, because the app may not be configured to respond to anything but the original name of the resource.

This would be a very welcome feature if it's doable.

**Comment by edward3h** [comment]
jte is just a template engine. These cache busting URLs are more a function of the server and/or build tool you are using.

In a project I'm making, I pass my `Assets` [instance into my template](https://github.com/edward3h/kv2/blob/main/views/src/main/jte/layout.jte#L24), then the template calls methods to get the css and js URLs. It's up to the server code to build the assets object with the right URLs in it.

**Comment by erbrecht** [comment]
I was thinking of doing something similar. I might take some inspiration from you.

I'm not suggesting that JTE do anything with the resources. Spring/Spring Boot already handles all the aspects of making the resource available at particular URLS (the original filename, plus the filename with the hash appended). Thymeleaf is a template engine, but it is somehow able to output a URL that includes the appended hash value for a resource. I thought something similar might be doable, but I definitely don't know enough about either of these projects (jte or thymeleaf) to understand how.

I appreciate your response, and I'll look more closely into your solution.
