### ISSUE TITLE
Empty String in attribute value should not remove it

### ISSUE THREAD

**Issue by casid** [casid/jte#255]
Especially for options this feature breaks the intent of the user:

```html
@Test
void attributes_String_empty_option() {
    codeResolver.givenCode("template.jte", "@param String value\n<option value=\"${value}\">Click</option>");

    templateEngine.render("template.jte", "", output);

    assertThat(output.toString()).isEqualTo("<option value=\"\">Click</option>");
}
```

The actual output currently is:
`<option>Click</option>`

This is semantically different to the expected output:
`<option value="">Click</option>`

My proposed solution would be to remove String attributes only if the String is `null`. @kelunik I think you already suggested this already before.

**Comment by kelunik** [comment]
Indeed, that's how I thought I'd work.
