### ISSUE TITLE
Possibly a bug(s) in the IntelliJ IDE plugin and JTE itself

### ISSUE THREAD

**Issue by bohdan-shulha** [casid/jte#257]
Hi @casid , 

We're doing a little bit strange thing: we wanted to save a little bit of efforts and we want to generate JSON with JTE.

Sorry for the screenshot, for now it is only to discuss what could possibly go wrong.

We have the following code and IDE tells that it can't parse the expression. However, the template itself works very well:
![telegram-cloud-photo-size-2-5359697089363300886-y](https://github.com/casid/jte/assets/533048/ed78c16d-910c-436a-8b3e-f8b6d63e8797)

Among that, the indentation made by the built-in formatter is _a little bit_ messed up, but that's not a big issue. :D

I believe that JTE (and IDE plugin) are not "looking" at the `type` annotation of the `script` tag and are treating all `script` tags as JS code.

I had similar issue when I was creating the importmap (it is json as well) and I had to `$unsafe` paths to the scripts like this:

```
    <script type="importmap">
    {
        "imports": {
            "alpine": "https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/+esm",
            "sortablejs": "https://cdn.jsdelivr.net/npm/sortablejs@1.x.x/+esm",
            "@ess/critical": "$unsafe{staticUrl("/js/critical.js")}",
            "@ess/admin/common": "$unsafe{staticUrl("/js/admin/common.mjs")}",
            "@ess/admin/components/relation-picker": "$unsafe{staticUrl("/js/admin/components/relation-picker.mjs")}",
            "@ess/admin/components/tournaments": "$unsafe{staticUrl("/js/admin/components/tournaments.mjs")}"
        }
    }
    </script>
```

P.S. Do you have any kind of "BuyMeACoffee" link? You're doing a great job and I'd love to support you with a coffee-sized donate. Hope I'm not alone. ;)

**Comment by kelunik** [comment]
Please, for your own sake, use a proper JSON library for this task.

**Comment by casid** [comment]
Yes, jte treats all `<script>` blocks as JavaScript. And 100% want to second @kelunik here. Producing JSON with a template engine is a nightmare to maintain.

Still, a few thoughts.

- I think the IntelliJ plugin expects a JSON element here. This should not produce an error: `"position": "${loop.getIndex() + 1}"`
- When writing to JS objects, the only safe slots to write to are JS Strings. That's the only thing the jte HTML encoder does when writing to a JS section. It escapes for a JavaScript String. Is there a reason you're using unsafe so much? Since you're actually writing to a JSON String escaping should be no problem unless you WANT to escape the String.
- `$unsafe{","}` is a bit weird, since that is essentially just `,`

> Do you have any kind of "BuyMeACoffee" link?

I don't, I'm doing this for fun :-) But thank you very much for the heads up!

**Comment by bohdan-shulha** [comment]
> Producing JSON with a template engine is a nightmare to maintain.

Yeah, I know. I needed a quick start for one of our devs, so I have allowed this, mostly as a temporary solution.

> This should not produce an error: "position": "${loop.getIndex() + 1}"

That's true - it works, but, unfortunately, consumer side expects an integer. 🤷 

> Is there a reason you're using unsafe so much?

As for importmap - yes, unfortunately. If I omit the unsafe - JTE starts escaping slashes and instead of `/some/file.js` I'm getting `\/some\/file.js`.

Also, we've got a strange escaping with this case:

`"name": "Top-G Makes History ..."` without unsafe will be `"name": "Top\-G Makes History ..."`.

All those escaping points make me think that this is just because JTE/Idea plugin are not expecting that `<script>` tag may contain JSON and apply the JS rules instead. 🤷 

TBH, I didn't expect that these issues will be fixed - for sure, very special case, but I wanted to get some discussion on this and make the "problem" visible. :)

**Comment by kelunik** [comment]
> mostly as a temporary solution.

There's no such thing, most temporary solutions will live forever. 😄

@casid As I said earlier, we shouldn't support variables in script tags at all and just make it a compile time error.

**Comment by bohdan-shulha** [comment]
We'll remove this hack along with the migrations of other pages from the heavy react ecosystem to jte. :)

I promise. :D

**Comment by casid** [comment]
> All those escaping points make me think that this is just because JTE/Idea plugin are not expecting that <script> tag may contain JSON and apply the JS rules instead. 🤷

I'm wondering why you run into problems with the escaped forward slashes. https://stackoverflow.com/a/1580682

![json-unescaped](https://github.com/casid/jte/assets/4077354/d1227459-6dda-43e0-9a7a-bf91c29718dc)
![json-escaped](https://github.com/casid/jte/assets/4077354/4b1457f0-1fdf-418b-951d-724a5cc2438c)

**Comment by bohdan-shulha** [comment]
Hm... Just tried to remove the `unsafe` option and the importmap seems to be working right now. But I remember that I have seen some problem with this back then. 

Anyways, the escaped `-` is still the case - Google fails to parse such sequence. 🤷 

<img width="512" alt="image" src="https://github.com/casid/jte/assets/533048/a74d9688-2e4e-4abd-98e4-a2cf9c519653">

_Screenshot from the google search console._
