### ISSUE TITLE
Support classes that are in no package

### ISSUE THREAD

**Issue by lsoares** [casid/jte#258]
If I have a class (in my case a Kotlin data class) in the root package, it can't be referenced in the templates. It's simply not found by jte generating a 500 error. Does it make sense to support it or do we assume that everyone uses a package? I bumped into this while creating a minimalistic tutorial for jte.

**Comment by lsoares** [comment]
but you can have a regular Kotlin program without package.
here, WebApp (with main) is in the root and it works fine.
<img width="180" alt="image" src="https://github.com/casid/jte/assets/674045/0b9eabdb-676f-43f6-90d9-1d540ad78e89">

**Comment by casid** [comment]
Yes, but you cannot import WebApp.kt from any other Kotlin package (at least if this works in Kotlin the same as in Java).

And jte template classes are generate by default in a package.

**Comment by lsoares** [comment]
do you mean this?

<img width="871" alt="image" src="https://github.com/casid/jte/assets/674045/d82cd09a-01c1-4b30-a989-9558ddf1f17e">

**Comment by casid** [comment]
Yes, in Java I get this compile error `Class 'X' is in the default package`. So this is working in Kotlin then?

Did you try this in your kte template then?
`@import X`

**Comment by lsoares** [comment]
yeah I think Kotlin is less restrictive in that regard.

HEre's there's no error in the jte plugin. only when I run it
<img width="1625" alt="image" src="https://github.com/casid/jte/assets/674045/30d0be08-58f4-47fe-8879-477a9187cf3a">

If I do @import Car as you said then there's an error in jte plugin which could have helped me but since it doesn't complain I was puzzled for a while.

**Comment by casid** [comment]
Closed this as not planned, because we can't do anything about it in jte itself.

I opened a ticket in the intellij plugin, to see if we can provide a better error message: https://github.com/casid/jte-intellij/issues/30
