### ISSUE TITLE
Replace intercepted tag with different content

### ISSUE THREAD

**Issue by dzikoysk** [casid/jte#297]
I'm currently making research around some existing template engines and jte looks quite promising. One of my requirements is the ability to replace a custom tag with some other content, e.g.:

```jsx
<Custom>
  <p>Text</p>
</Custom>
```

with:

```jsx
<article>
  <section>
    <p>Text</p>
  </section
</article>
```

I was playing a little bit with html interceptor:

```java
templatingEngine.setHtmlTags("custom");
templatingEngine.setHtmlInterceptor(new HtmlInterceptor() {
    @Override
    public void onHtmlTagOpened(String name, Map<String, Object> attributes, TemplateOutput output) {
        if (name.equals("Custom")) {
            output.writeUserContent("abc");
        }
    }
    @Override
    public void onHtmlTagClosed(String name, TemplateOutput output) {
        if (name.equals("Custom")) {
            output.writeUserContent("cdf");
        }
    }
```

but this API seems to be a little too simple for that use case. I wonder if there's some other way to achieve this kind of results.

**Comment by casid** [comment]
Not really.

The idiomatic jte way to do this is to call another template, e.g.

@template.custom(body = @`
    <p>Text</p>
`)
