### ISSUE TITLE
The ` syntax in the <script> tag in a jte extension file doesn't work.

### ISSUE THREAD

**Issue by stella6767** [casid/jte#303]
## .jte file in intellij

![image](https://github.com/casid/jte/assets/65489223/f0c58d49-e213-46c0-b583-ed13a75c17da)

## .html file in intellij

![image](https://github.com/casid/jte/assets/65489223/ef575e8a-ab31-4838-9370-722062fc9732)

I'm not sure if this should be an issue here, but maybe there is a solution?

**Comment by casid** [comment]
You could put your script in a `@raw` section, to prevent jte from interfering with js.

https://jte.gg/html-rendering/#raw-output
