### ISSUE TITLE
Initial response time is slower on first request than on subsequent requests

### ISSUE THREAD

**Issue by Jerbell** [casid/jte#306]
Hi, this is more of a query than an issue.

We use KTE templates and the gradle command: `jte { generate() }`.
I notice that the initial requests have a slower reponse time, and I don't think it's to do with our code.

```
200 GET https://localhost:32327/xxx from 127.0.0.1 in 246ms
200 GET https://localhost:32327/xxx from 127.0.0.1 in 15ms
```
and
```
200 GET https://localhost:32327/yyy from 127.0.0.1 in 43ms
200 GET https://localhost:32327/yyy from 127.0.0.1 in 8m
```

Is this something you notice & expected behaviour, or something on our end?

TIA!

**Comment by casid** [comment]
Hi @Jerbell,

this is expected behavior, since the class loader needs to load the generated classes on the first request. Probably at some point the JIT will kick in and make everything faster too.


Cheers

**Comment by Jerbell** [comment]
Thanks for the explanation - all good :)
