### ISSUE TITLE
suggestion: default value for nulls when rendering

### ISSUE THREAD

**Issue by tomholub** [casid/jte#31]
I have a parameter that may be null. It would be great to be able to define default values in the template. Currently:

```
@param String user

Hello @if(user != null)${user}@else unknown user @endif
```

Would ideally be

```
@param String user

Hello ${user ?: "unknown user"}
```

The first example is not so bad when it's just `user`, but for things like `existingEkmKeyPairRes.body().getKeypair().getFingerprint()` it gets really verbose, and defining a shorter variable above doesn't make it much less verbose either.

Not a huge priority, but nice to have :+1:

**Comment by kelunik** [comment]
Hey @tomholub, there are a number of reasons for not supporting such a syntax:
 - Complicates parsing the expressions, as we'd have to parse the Java code and understand it (current and future syntax)
 - There might be conflicts with future Java syntax
 - Complicates autocomplete, which is currently entirely powered by the IntelliJ Java autocomplete inside expressions

[Vue has deprecated their filter syntax](https://v3.vuejs.org/guide/migration/filters.html#_2-x-syntax) for similar reasons in Vue 3.

I'd suggest introducing a helper function for now that can be statically imported:

```
${fallbackIfNull(something.getKeyPair().getFingerprint(), "Unknown")}
```

If your fallback is expensive to compute, a method reference or lambda might be appropriate.

**Comment by tomholub** [comment]
I had the same thought with the helper function. Thank you for the explanation, that's what I'll do.
