### ISSUE TITLE
jte auto-import producing weird statements

### ISSUE THREAD

**Issue by tomholub** [casid/jte#32]
Sorry for the issue spam on a Saturday :)

When I have the following

```
@import com.flowcrypt.server.jte.JteFunctions
@param ...

...
```

and I need `HttpMethod` somewhere in the template, which I auto-import with alt+enter, it will produce this:

```
@import com.flowcrypt.server.jte.JteFunctions;import org.eclipse.jetty.http.HttpMethod
@param ...

...
```

I would have expected this:

```
@import com.flowcrypt.server.jte.JteFunctions
@import org.eclipse.jetty.http.HttpMethod
@param ...

...
```

**Comment by kelunik** [comment]
This is a known issue, but we're unsure how to solve this, yet. Might be solved by an auto formatter instead of directly during auto complete.

**Comment by casid** [comment]
@tomholub I've adjusted the jte plugin to produce clean imports: https://github.com/casid/jte-intellij/commit/04afdadd9c6c85140399f52310cd3d4c23a7a9e0

I'll release a new plugin version within the next days!

**Comment by tomholub** [comment]
Thanks!

**Comment by casid** [comment]
The jte-intellij plugin 1.2.0 was approved by JetBrains and is available with this fix.
