### ISSUE TITLE
Spring Boot integration and binary rendering

### ISSUE THREAD

**Issue by ltanguy** [casid/jte#327]
Hello,

I was wondering why the spring boot module doesn't include an option to enable binary rendering. Is there a technical reason for not enabling it in this context ?

**Comment by ltanguy** [comment]
This feels to me as a rare edge case, typically for projects with a tight coupling with Spring MVC (like the one referenced in this commit).
Would it make sense to reinstate this ability through an auto-configuration option, disabled by default ?

**Comment by casid** [comment]
I think the reasoning was that, the performance difference between binary/string templates would be neglectable compared to the overhead of Spring Boot. The way it is, it is less complicated for users and compatible with all interception mechanisms that spring offers.

@tschuehly what do you think?

**Comment by tschuehly** [comment]
Yes, that is a good explanation.
What do you want to achieve with binary rendering? @ltanguy

**Comment by ltanguy** [comment]
Nothing very specific actually, probably more the beauty of squeezing as much performance as possible, but I agree that the difference won't probably be significative in most cases.
I'm not sure to see where the use case of binary rendering fits, as almost every web application will rely on a framework of some sort (Spring, Quarkus, ...) that will have similar requirements.

**Comment by edward3h** [comment]
Many applications make network calls to databases or other services. Once you are hitting the network for the data for your models, the CPU cost of binary vs text rendering is basically irrelevant.
