### ISSUE TITLE
Pass dynamic HTML Content to template

### ISSUE THREAD

**Issue by techniqs** [casid/jte#331]
I would love to pass to the jte/kte files some html formatted string which comes from my db to make it more dynamic, is there anyway to do that? I tried to pass a string and obviously it renders the whole string instead of trying to html render it and seems like Content is only for sharing code between templates so Im kinda clueless. 

Would appreciate any help :)

**Comment by kelunik** [comment]
Sure! You can output raw HTML using `$unsafe{...}` instead of `${...}`.
