### ISSUE TITLE
Template compiler does not support preview features

### ISSUE THREAD

**Issue by spinscale** [casid/jte#34]
I am using jte with java 15 and enabled previews, as I want to use records. However, if I have a record used in a template I get the following exception:

```
gg.jte.TemplateException: Failed to compile template, error at
error: classfile for /Users/alr/devel/spinscale/javalin-elasticsearch-client/out/production/classes/model/Person.class uses preview features of Java SE 15.
  (use --enable-preview to allow loading of classfiles which contain preview features)
1 error
```

So, having this record, using `--enable-preview` to activate such features for regular compilation seems it is not passed through the template compiler.

```
public record Person(String firstName, String lastName, String employer) {}
```

Template can look like this

```
@import model.Person;
@param Person person
{ "name" : { "first" : "${person.firstName()}", "last" : "${person.lastName()}"}, "employer" : "${person.employer()}" }
```

```
try (StringOutput output = new StringOutput()) {
    templateEngine.render("person.jte",  Map.of("person", person), output);
    return output.toString();
}
```

Is there any possibility to enable preview features for the template compiler? The `ClassFilesCompiler` class did not look like it.

**Comment by casid** [comment]
@spinscale is this happening when you compile with the maven plugin?

Or is it during regular development?

**Comment by spinscale** [comment]
that happens during regular development/when running the application, when the application itself is started with `--enable-preview`

Not using maven at all in that project

**Comment by casid** [comment]
Interesting, other project settings are picked up by the compiler tool. Probably because `--enable-preview` isn't easy to determine at runtime since it just affects the compiler. I'd rather not add something like this to detect it:

https://stackoverflow.com/questions/58327000/programmatically-detect-preview-mode-in-jre

I think the best option would be to allow the `TemplateEngine` to be configurable with additional compiler arguments. I'll try to put something together!

**Comment by spinscale** [comment]
+100 for less magic, but more explicit configuration :-)

Thanks for diving into it!

**Comment by casid** [comment]
100% agree! I just pushed a commit to pass compiler arguments to the template engine.

In your case it should work with something like this, where you setup the engine:
`templateEngine.setCompileArgs("--enable-preview", "--release", "" + Runtime.version().feature());`

To try it, you'd need to clone the repository and build `1.5.0-SNAPSHOT` though. If this works I'll add parameters for it to the maven plugin, too!

**Comment by spinscale** [comment]
tested and works!

**Comment by casid** [comment]
Awesome, thanks for testing it so quickly!

I will adjust the maven plugin and then close this issue, if that's okay with you.

**Comment by spinscale** [comment]
hey! Any chance of a new release to get this out? 😀

**Comment by casid** [comment]
Thanks for the reminder, it's about time for a new release!

**Comment by casid** [comment]
Hey @spinscale release 1.5.0 is available on maven central :-)
