### ISSUE TITLE
Generic template

### ISSUE THREAD

**Issue by guxingke** [casid/jte#348]
```
@param columns: List<Column<Application>>  = emptyList()
<select name="__sort">
    <option>---</option>
    @for(obj in columns)
        @if(obj.comparator !=null)
            <option value="-${obj.name}"
                    selected="${rm.getOrDefault("__sort", "") == "-${obj.name}"}">
                -${obj.title}</option>
            <option value="${obj.name}"
                    selected="${rm.getOrDefault("__sort", "") == obj.name}">${obj.title}</option>
        @endif
    @endfor
</select>
```

if I want to extract code as template,
Application as a generic parameter

---
this way it can be reused, It seems not possible yet.

**Comment by casid** [comment]
Welcome @guxingke! I'm sorry, templates with generic types are not supported at the moment.

**Comment by casid** [comment]
If the template is not interested about the generic types, I think wildcards should work.

In your example `List<Column<?>>`.

**Comment by guxingke** [comment]
> If the template is not interested about the generic types, I think wildcards should work.
> 
> In your example `List<Column<?>>`.

-------
thank you , yes , in the current scenario, this solution is sufficient.
