### ISSUE TITLE
Provide a way to avoid line-ending

### ISSUE THREAD

**Issue by albertorobles2000** [casid/jte#376]
Hi!

I'm starting to investigate JTE to try to migrate a velocity project.
I have some complex conditions and I cannot do everything in just one line but I want the output rendered in one line.
For example if for this:
```
l = [@if (A) A @endif @if (B) B @endif ... @if (Z) Z @endif]
```
I will get `l = [A B C E G J ... Z ]`
I cannot put all those condtions in one line, but the output has to be all in one line. Is it implemented?
In velocity I can do:
```
l = [ #*
#*--*##if (A)
A#*
#*--*##end
#*--*##if (B)
B#*
#*--*##end
#*--*##if (C)
C#*
#*--*##end
...
#*--*#]
```
And the output will be `l = [A B C E G J ... Z ]`

**Comment by edward3h** [comment]
What kind of file are you trying to produce?

**Comment by albertorobles2000** [comment]
A raw file. In our case we have velocity integrated in a code generator that process an input file and generates code for the given file for a bunch of APIs C/C++/Java/Python/C#

**Comment by casid** [comment]
Can only second @edward3h point. jte is heavily focused on generating HTML. For generating code I would (personally) definitely use a different library, like JavaPoet for Java Code.
