### ISSUE TITLE
JTE Spring Boot properties aren't in dash casing

### ISSUE THREAD

**Issue by mhalbritter** [casid/jte#382]
Hello,

i've noticed that the properties in the [`spring-configuration-metadata.json`](https://github.com/casid/jte/blob/main/jte-spring-boot-starter-3/src/main/resources/META-INF/spring-configuration-metadata.json) file are in camel case (e.g. `gg.jte.usePrecompiledTemplates`).

If you take a look at the metadata included in Spring Boot itself, [it's dash cased](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json#L10).

Btw, there's a [plugin](https://docs.spring.io/spring-boot/specification/configuration-metadata/annotation-processor.html#appendix.configuration-metadata.annotation-processor.configuring) which automatically creates the metadata files from the property files.

Would you be open to change the properties to dash-casing (e.g. `gg.jte.use-precompiled-templates`) for better consistency?

**Comment by casid** [comment]
Hi @mhalbritter,

thanks for the feedback, and yes I have no stakes in how the spring properties are named and consistency with the Spring Boot conventions makes a lot of sense.

What's the recommended way to make breaking changes like this? For instance, it would be bad if `gg.jte.usePrecompiledTemplates` wouldn't be applied when users upgrade and don't read the patch notes carefully.

I could think of keeping the old properties and deprecating them for removal and to throw an exception if those are still set? But maybe there is a better way?

@atomfrede, @tschuehly would you be ok with this change, too?

**Comment by atomfrede** [comment]
Totally fine. We could print a warning for e.g. 1 release and ignore them in the next (or throw an exception)

**Comment by tschuehly** [comment]
@casid @mhalbritter 
This shouldn't be a breaking change as Spring Boot uses relaxed binding: https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.typesafe-configuration-properties.relaxed-binding

**Comment by kelunik** [comment]
@casid Breaking changes should only be shipped in major releases. We can likely read both versions with the new name having precedence and log a warning if the old name is used? Then drop the old path in the next major.

**Comment by casid** [comment]
Thanks for the update and clarification @mhalbritter. @tschuehly already made the changes, so this will be part of the next release :-)

**Comment by mhalbritter** [comment]
Great! Thanks a lot!
