### ISSUE TITLE
LiveReload with Spring

### ISSUE THREAD

**Issue by tschuehly** [casid/jte#399]
Spring Boot automatically starts a livereload server that can be connected with:
```
<script src="http://localhost:35729/livereload.js"></script>
```

But to trigger a live reload, Spring needs to be notified that a template has changed.

This is done with a FileSystemWatcher. I've created a PR: https://github.com/casid/jte/pull/398

**Comment by casid** [comment]
Thanks for the PR @tschuehly!

Does the `ContextRefreshedEvent` lead to a restart of the application, or does it only trigger a browser reload?

Changing jte templates doesn't require an application restart, so it would be nice if on the browser would reload.

**Comment by tschuehly** [comment]
@casid 
It only triggers a browser reload.

**Comment by casid** [comment]
That's awesome then! I've just merged the PR. Thanks for the clarification!

**Comment by frederikb** [comment]
If it's not too much trouble we would be glad to have a bugfix release containing this change.

**Comment by casid** [comment]
Hi @frederikb, not at all!

I'll create a new release tomorrow :-)

**Comment by casid** [comment]
@frederikb 3.1.14 is out, containing this feature.

**Comment by frederikb** [comment]
Thanks a lot, @casid, that was much faster than expected!
And thanks @tschuehly, my first try was successful. 

I'll test drive it for a bit and would report back if anything pops-up. Happy weekend.
