### ISSUE TITLE
Ability to create custom tags

### ISSUE THREAD

**Issue by adpande** [casid/jte#4]
Can I create custom tags like @if and @for ?

The idea is to create a vue component using the tag and generate java script. The listen to event using ws. Something similar to blazor .net framework.

**Comment by casid** [comment]
Welcome @adpande!

Yes, you can absolutely create custom tags. You need to put them into the `tag` directory within your jte root folder. For instance, you can create a jte file like this:
`tag/vue/component.jte`

In other templates you can then call it like this:
`@tag.vue.component()`

For more details, have a look at the [tag syntax documentation](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#tags).

**Comment by adpande** [comment]
Hey, thanks @casid! I will try, I think this will solve it.

**Comment by casid** [comment]
@adpande thanks for the follow up! Good luck with your vue js tags, that sounds very intesting :-)

Whenever you have something to share/show, let me know, it's nice to see what other devs do with jte.
