### ISSUE TITLE
Add @var feature

### ISSUE THREAD

**Issue by IvanPizhenko** [casid/jte#41]
Feature request: Add ability to declare local variables.
Example usage:
```
@import ....

@param SomeClass someObject 

@var innerObject = someObject.get().very().deeply().located().internal().object()
```
Can be translated directly to Java 11 ```var .... ```
for Java 8, if required, can be with optional type declaration:
```
@var OtherClass innerObject = someObject.get().very().deeply().located().internal().object()
```

More examples:
```
@if (request.isSuccessful())
  @var resultObject = request.getResult().getResultObject(). .... /// few more calls
  .... // use resultObject
@endif
```

**Comment by casid** [comment]
Hey @IvanPizhenko !

Current syntax for variables is:

```
!{var innerObject = someObject.get().very().deeply().located().internal().object();}
```

If you type `!` the intellij plugin will suggest a live template for a variable declaration.

The syntax you suggested is a little cleaner (and was the initial idea), but I couldn't get inline refactorings in IntelliJ working  that way. IntelliJ needs the whole expression as injected Java fragment.

**Comment by casid** [comment]
I've updated the documentation with a variables section: https://github.com/casid/jte/commit/4dc307a6d80d376d29047563d19267936defea19

**Comment by IvanPizhenko** [comment]
Wow, that's great! I didn't know this is already supported.

**Comment by IvanPizhenko** [comment]
Yes, the docs didn't say anything about this, so thanks for updating the docs!
