### ISSUE TITLE
Dynamic rendering

### ISSUE THREAD

**Issue by dragonnikkirocks** [casid/jte#44]
For the template to render a variable or something, is it necessary that it's placeholder should be present in the .jte file. If I want to read a json file or something and add a extra variable during runtime, is it possible?
TIA

**Comment by casid** [comment]
Hey @dragonnikkirocks, tags in templates are statically typed and cannot be invoked dynamically. But I'm not sure if this is what you want to do.

Can you provide some example code of what you'd like to achieve?

**Comment by dragonnikkirocks** [comment]
Hi@casid, Thanks for the prompt reply
My use case is like this:
Suppose I have to render a document with employee details. My data model has values like user name, position and so on. Suppose I have an extra detail like 'nickname' which has to be rendered only if available.  Is this possible?

**Comment by casid** [comment]
Oh, yes. You can use [control structures](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#control-structures) to do this.

Something like:

```html
<p>${employee.getName()}</p>
<p>${employee.getTitle()}</p>
@if(employee.getNickname() != null)
    <p>${employee.getNickname()}</p>
@endif
```
