### ISSUE TITLE
Failed to compile MyPage.jte, error at line 43: Illegal HTML attribute name @if(myValue.equals("option1"))! Expressions in HTML attribute names are not allowed.

### ISSUE THREAD

**Issue by IvanPizhenko** [casid/jte#45]
Trying to write thing like this:
```html
@param String myValue

...

<select name="myValue">
<option value="option1" @if(myValue.equals("option1")) selected @endif>Option 1</option>
<option value="option2" @if(myValue.equals("option2")) selected @endif>Option 2</option>
<option value="option3" @if(myValue.equals("option3")) selected @endif>Option 3</option>
</select>
```
and getting that error. 

Can you please suggest how to overcome this?

I think I could do:
```html
@if(myValue.equals("option1"))
<option value="option1" selected>Option 1</option>
@else
<option value="option1">Option 1</option>
@endif
```
but that repeats too much the same thing.

If that's really not supported, count on this as non-priority feature request. The above workaround works.

**Comment by kelunik** [comment]
You can use that I think:

```
<option value="option1" selected="${myValue.equals(" option1"}">Option 1</option> 
```

**Comment by IvanPizhenko** [comment]
> You can use that I think:
> 
> ```
> <option value="option1" selected="${myValue.equals("option1")}">Option 1</option> 
> ```

Doesn't work. Try following HTML
```
<select id="cars">
  <option value="volvo" selected="false">Volvo</option>
  <option value="saab" selected="true">Saab</option>
  <option value="opel" selected="false">Opel</option>
  <option value="audi" selected="false">Audi</option>
</select>
```
Shows "Audi"

**Comment by casid** [comment]
@IvanPizhenko did you try @kelunik's suggestion though?

jte only jumps in, if the attribute value is an expression. Try change your example above to:

```html
<select id="cars">
  <option value="volvo" selected="${false}">Volvo</option>
  <option value="saab" selected="${true}">Saab</option>
  <option value="opel" selected="${false}">Opel</option>
  <option value="audi" selected="${false}">Audi</option>
</select>
```

Will render this HTML:

```html
<select id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab" selected>Saab</option>
  <option value="opel">Opel</option>
  <option value="audi">Audi</option>
</select>
```

I think I only properly described this in the [release notes](https://github.com/casid/jte/releases/tag/1.4.0) so far. Will update the documentation, too.

**Comment by casid** [comment]
@IvanPizhenko I've updated the documentation: https://github.com/casid/jte/blob/master/DOCUMENTATION.md#html-rendering

**Comment by IvanPizhenko** [comment]
@casid, that's great, thank you!
