### ISSUE TITLE
option to preserve html comments

### ISSUE THREAD

**Issue by Fender123** [casid/jte#47]
Hi,

we are using nginx serversideincludes infront of our application. nginx SSIs are expressed as html comments (https://nginx.org/en/docs/http/ngx_http_ssi_module.html) (`<!--# include file="footer.html" -->`)
Unfortunately jte strips all html comments without providing an option keep them which removes all nginx SSI expressions as well.

Could you please provide an option to keep html comments as they are.

My current workaround is:
```
$unsafe{"<!--"}# include virtual="${virtual}" -->
```

**Comment by casid** [comment]
Hey @Fender123!

thanks for reporting this. When we decided to omit comments in HTML mode we couldn't think of a reason one would want them in the output. Didn't think about serverside includes. Let me know if this change would work for you: https://github.com/casid/jte/commit/9ae8c37be5b6ae385b050a71c970043fec1a131f

**Comment by kelunik** [comment]
It's probably a good idea for another policy? You probably want to strip comments except for SSI includes?

**Comment by casid** [comment]
@kelunik you can still use jte-style comments if you want to omit them: `<%-- This will never be rendered. --%>`.

**Comment by Fender123** [comment]
yes fixes the problem!

**Comment by casid** [comment]
Awesome, thanks for the feedback @Fender123. I'll put together a bugfix release this week and close this issue once it is out.

**Comment by casid** [comment]
I tried to publish 1.5.1 to maven central today, but ran into timeouts. Never had that happening before. I'm wondering JFrog's announcment to sunset jcenter is driving lots of people to upload their stuff to maven central right now, causing bandwidth problems.

I'll keep you posted.

**Comment by casid** [comment]
@Fender123 this morning publishing to maven central worked again. 1.5.1 is live containing this fix 👍
