### ISSUE TITLE
smart attributes broken after boolean attribute

### ISSUE THREAD

**Issue by Fender123** [casid/jte#50]
The fix in https://github.com/casid/jte/issues/46#issuecomment-771633865_ broke smart attributes handling if they follow a boolean attribute:

```
// hidden=false
<div data-hidden="${hidden}" data-test></div>  --> <div data-test></div> // correct
<div data-test data-hidden="${hidden}"></div>  --> <div data-test data-hidden="false"></div> // !!! wrong
```

it seems to be only happening in version 1.5.1 if the smart attribute directly follows a boolean attribute

**Comment by casid** [comment]
Thanks for reporting! I fixed it. 

I think this bug was there before already. I reset to `1.5.0` and (after disabling the HTML policy), the new unit test failed there as well.

I made some other changes this weekend (automatic module name, upgrade to latest OWASP escaping lib). Will publish a new release with this fix now.

**Comment by casid** [comment]
Damn, timeouts again on sonatype. I'll give it another try tomorrow morning.

```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6:deploy (injected-nexus-deploy) on project jte-deploy-nexus: Remote staging failed: Failed to retrieve remote metadata gg.jte/maven-metadata.xml: Could not transfer metadata gg.jte/maven-metadata.xml from/to ossrh (https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ggjte-1016): Transfer failed for https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ggjte-1016/gg/jte/maven-metadata.xml: Operation timed out (Read failed) -> [Help 1]
```

**Comment by casid** [comment]
Now the upload worked, `1.5.2` is on maven central :-)
