### ISSUE TITLE
Partial server side HTML rendering

### ISSUE THREAD

**Issue by renannprado** [casid/jte#55]
> Disclaimer I haven't dig too much into `jte` nor tried it yet, so excuse me if I'm saying something stupid here

First of all, it's very nice to see a fresh kid in town as it seems that the other templating engines for Java are not evolving anymore.

I would like to ask if there are plans/possibility to implement _partial HTML rendering_. There is probably a better term for that, but what I mean here is:

1. click on a button
2. the browser goes to server
3. the server processes the request
4. renders a new part of the HTML and sends just a part of it to the browser
5. browser renders a small part of the screen

So that this:

```html
.
.
.
<div>
    <button>Click me</button>
<div>
.
.
.
```

becomes, for example, this:

```html
.
.
.
<div>
    <button>Click me</button>
    <h5>Message from server</h5>
</div>
.
.
.
```

Without a full browser refresh.

I could be wrong here again, but I believe that's one of the features of [vaadin](https://vaadin.com/), but the last time I tried it, I got sick of it pretty quickly.

That being said, if this is not possible today, I bet it's not trivial to implement. Though could be a _very nice_ feature to have IMHO.
I'm not here only to ask for the feature, but if there's a possibility/interest in doing it, I would like to help to implement such a feature with some guidance, if I/maintainer have the time.

**Comment by casid** [comment]
Hey @renannprado,

thanks for the heads up! I've played a bit with partial rendering, bit like Amazon does it in their checkout flow, but there's nothing serious to see yet.

I'd love to try an HTMX integration one day, but haven't found the time yet:
https://htmx.org/

**Comment by renannprado** [comment]
@casid I've never heard of `htmx`, but it looks pretty good at first sight. At the moment I cannot foresee that `jte` would need some kind of support in order to use `htmx`, right? it should be possible to compile & render partial `jte` files, right?

**Comment by kelunik** [comment]
@renannprado Yes.

**Comment by renannprado** [comment]
@casid looks like this lib is also interesting, but nowadays it's only easy to find information about it + Ruby on Rails: https://hotwire.dev/

**Comment by izogfif** [comment]
I'm not sure how this is related to JTE or any template rendering engine at all. You can do this:

Let's say an https://example.com/page.html is opened in the browser.

1) User clicks on a button on this page.
2) JavaScript in browser intercepts button click event.
3) JavaScript sends a request to the server to a special endpoint: https://example.com/partial.html
4) Server processes this request, generates an HTML code and sends it to browser.
5) JavaScript in browser receives this HTML code from the server and inserts it into page, without reloading page at all.

**Comment by casid** [comment]
Just cleaning up issues and closed this, since this would be something built on top of jte.

**Comment by don41382** [comment]
@izogfif Take a look at [htmx.org ](https://htmx.org/). It perfectly integrates with JTE. It allows you todo exactly what you want. I am currently using it on a project with Spring Boot + JTE + HTMX.
