### ISSUE TITLE
Add gradle plugin configuration example with Kotlin script

### ISSUE THREAD

**Issue by IvanPizhenko** [casid/jte#58]
Please add Kotlin script equivalent code. Currently it is only in the Groovy:

```groovy
import gg.jte.ContentType
import java.nio.file.Paths

plugins {
    id 'java'
    id 'gg.jte.gradle' version '${jte.version}'
}

dependencies {
    implementation('gg.jte:jte:${jte.version}')
}

tasks.precompileJte {
    sourceDirectory = Paths.get(project.projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = Paths.get(project.projectDir.absolutePath, "jte-classes")
    compilePath = sourceSets.main.runtimeClasspath
    contentType = ContentType.Html
}

tasks.precompileJte {
    dependsOn(tasks.compileJava)
}

tasks.test {
    dependsOn(tasks.precompileJte)
}
```
Struggling with converting this part to Kotlin:
```groovy
tasks.precompileJte {
    sourceDirectory = Paths.get(project.projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = Paths.get(project.projectDir.absolutePath, "jte-classes")
    compilePath = sourceSets.main.runtimeClasspath
    contentType = ContentType.Html
}
```

**Comment by casid** [comment]
Hmm, @iRebbok initially posted some example code to use the plugin with kotlin script: https://github.com/casid/jte/pull/53 (you need to click expand to see it)

I haven't used kotlin script with gradle so far, so I'm probably of little help here.

What error is in the gradle output, when you compile this part?

**Comment by IvanPizhenko** [comment]
I'm just trying to write `build.gradle.kts` in the IntelliJ and it shows syntax errors if I copy that as is and even add imports.

**Comment by IvanPizhenko** [comment]
Thanks, I've reviewed example in the #53 but it doesn't work. Not sure why. Just getting:
```kotlin
tasks.compilerMojo { // <<< ERROR: Unresolved reference compilerMojo
}
```

Similarly:
```kotlin
tasks.precompileJte { // <<< ERROR: Unresolved reference precompileJte
}
```

**Comment by IvanPizhenko** [comment]
Reloaded project in the intellij - the error have gone. somehow intellij doesn't pick it up on the fly.

**Comment by casid** [comment]
I just tried a sample configuration using `build.gradle.kts`. What a mess this is. And people complain about maven's XML structure - lol.

IntelliJ seems to display everything in red. However, I can run gradle build, that gives me this error:

```
build.gradle.kts:19:35: Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public val NamedDomainObjectContainer<Configuration>.runtimeClasspath: NamedDomainObjectProvider<Configuration> defined in org.gradle.kotlin.dsl
```

I googled `sourceSets.main.runtimeClasspath` in gradle kotlin dsl, nothing of the proposed solutions worked, I'm giving up.

```kotlin
import gg.jte.ContentType
import java.nio.file.Paths

plugins {
    java
    id("gg.jte.gradle") version "1.7.0"
}

group = "org.example"
version = "1.0-SNAPSHOT"

dependencies {
    implementation("gg.jte:jte:1.7.0")
}

tasks.precompileJte {
    sourceDirectory = Paths.get(project.projectDir.absolutePath, "src", "main", "jte")
    targetDirectory = Paths.get(project.projectDir.absolutePath, "jte-classes")
    compilePath = sourceSets.main.runtimeClasspath
    contentType = ContentType.Html
}

tasks.precompileJte {
    dependsOn(tasks.compileJava)
}

tasks.test {
    dependsOn(tasks.precompileJte)
}
```

**Comment by casid** [comment]
Oh, wow! Glad you got it working!

Would you post your configuration here, or create a pull request to enhance the documentation?

I have no idea how to resolve that compilePath problem.

**Comment by IvanPizhenko** [comment]
Sure, I will post my config when I get it working

**Comment by IvanPizhenko** [comment]
what is "compilePath"?

**Comment by IvanPizhenko** [comment]
Solution is a bit messy:
```kotlin
  compilePath = project.the<SourceSetContainer>()["main"].runtimeClasspath
```

**Comment by IvanPizhenko** [comment]
> What a mess this is. And people complain about maven's XML structure - lol.

Definitely, this is better and shorter mess than Maven.

**Comment by IvanPizhenko** [comment]
So here is what I ended up with:
```kotlin
plugin {
  id("gg.jte.gradle") version("1.6.0")
}

tasks.precompileJte {
  sourceDirectory = Path.of(project.projectDir.absolutePath, "src", "main", "jte")
  targetDirectory = Path.of(project.projectDir.absolutePath, "build", "resources", "main")
  compilePath = project.the<SourceSetContainer>()["main"].runtimeClasspath
  contentType = gg.jte.ContentType.Html
  shouldRunAfter(tasks.compileKotlin)
}
```
You may post this one into docs, but edit `sourceDirectory` and `targetDirectory` to match your Groovy example, because I have a bit different ones.

**Comment by IvanPizhenko** [comment]
Edited above, forgot to add dependency for test

**Comment by casid** [comment]
Thank you @IvanPizhenko! I've updated the documentation 👍

**Comment by IvanPizhenko** [comment]
Thank you!
