### ISSUE TITLE
Any plan to add Java 1.8 compatible?

### ISSUE THREAD

**Issue by linux-china** [casid/jte#6]
Now I use Java 14, and all is fine.  And you know some Java developer still use Java 1.8.    Thanks for your great job :)

**Comment by casid** [comment]
Hey @linux-china, thanks for the heads up!

Unfortunately, there are no plans to add support for Java 8. The code generator relies on a few features that aren't available in Java 8 (mostly the var keyword).

I'm sure over time more and more enterprise projects will adopt JDK 11.

Also, congrats on being on Java 14 already, we're still on Java 11.

**Comment by casid** [comment]
@linux-china since `1.6.0` jte supports Java 8 :-)
