### ISSUE TITLE
DirectoryCodeResolver stores entries in the modificationTimes map even if template is not found

### ISSUE THREAD

**Issue by rferreira** [casid/jte#65]
If you try to resolve a non existing view name, you still end up with an entry in the modificiationTimes map potential leading to a resource leak: 

https://github.com/casid/jte/blob/master/jte/src/main/java/gg/jte/resolve/DirectoryCodeResolver.java#L31

Relevant method: 
```java
    @Override
    public String resolve(String name) {
        try {
            Path file = root.resolve(name);
            modificationTimes.put(name, getLastModified(file));
            return new String(Files.readAllBytes(file), StandardCharsets.UTF_8);
        } catch (NoSuchFileException e) {
            return null;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
```

**Comment by casid** [comment]
@rferreira thanks for reporting, this should be fixed in https://github.com/casid/jte/commit/a3369e162f9c81870d963165c72b0b6b012fe099 👍
