### ISSUE TITLE
[Feature request] Tag parameters should allow for variable interpolation

### ISSUE THREAD

**Issue by rferreira** [casid/jte#71]
First of all, sorry for the onslaught of requests lately but I'm trying JTE in a non trivial sized project and running into some corner cases. This is simply a feature request but it would be nice if you could interpolate in arguments being passed to tags, for example: 

```
@param String name
<h1>Hello ${name}</h1>
```

today, if you try to call it like this: 
```
@tag.foo (name = "${user.firstName} ${user.lastName)") 
```

no interpolation will occur and the string "${user.firstName} ${user.lastName)" will be passed to the tag verbatim.

**Comment by casid** [comment]
No worries!

jte already supports that with `gg.jte.Content` 👍 

```
@param gg.jteContent name
<h1>Hello ${name}</h1>
```

You can call it like this:

```
@tag.foo (name = @`${user.firstName} ${user.lastName}`) 
```

It's pretty much a lambda under the hood, so very fast. And you get full completion in IntelliJ.

**Comment by rferreira** [comment]
oh you are too good sir, thank you!
