### ISSUE TITLE
Kte support in Javalin

### ISSUE THREAD

**Issue by Jerbell** [casid/jte#74]
I created this issue - perhaps I should have left it to you:
https://github.com/tipsy/javalin/issues/1206

Just wondering - it is expected that the kte templates be placed in `src/main/kte` instead of `src/main/jte`?

If so I'll need to change/remove the issue.

**Comment by casid** [comment]
@Jerbell I'd recommend to place them in `src/main/jte`. The IntelliJ plugin looks into `jte` directories to resolve file references. For possible migrations it is also possible to call `.kte` from `.jte` templates and the other way round, but only if both are in the same root directory.

Thanks for adding the javalin issue. I've planned to update the javalin plugin to use jte 1.9.0, I'll have a look at kotlin support, too.

**Comment by Jerbell** [comment]
Based on your comment in the other issue - you only need the `jte-kotlin` dependency during dev or the precompileJte phase of your build - is that correct?

I'll leave this all up to you then.  Sounds like you had a plan and I butted in :)

**Comment by Jerbell** [comment]
Oh - I migrated from JTE to KTE and everything seems happy.  Couple of very minor things - might post them as issues.

**Comment by casid** [comment]
I've created a PR on the Javalin project. Let's see what tipsy says about it :-)

I'm closing this issue now, since there's nothing more that can be done in the jte repo.

Tha Javalin PR is here: https://github.com/tipsy/javalin/pull/1207
