### ISSUE TITLE
Gradle multi-module, Windows 10 & KTEs lock shared jars

### ISSUE THREAD

**Issue by Jerbell** [casid/jte#77]
There's a combination we use of Windows, Gradle (latest version) and precompileJte (now KTE), which caused shared built jars to be "locked" so a gradle clean won't work.
This problem didn't happen with JTEs and plugin & library version 1.8, but happens now with KTEs & plugin & library version 1.9.
Could it be a file/resource opening and you're not closing it perhaps?
I can do a gradle clean on the `compileKotlin` task for instance, but as soon as I do `precompileJte` then this problem happens so I'm fairly sure there's an issue somewhere in the jte kotlin module.
I tried it all on Ubuntu and it seems fine.

**Comment by casid** [comment]
Can you try if this happens with version 1.8.0 and kte templates as well?

**Comment by Jerbell** [comment]
Same thing happens with 1.8.0.
When I have a bit of time I could create a mini-project to try and demonstrate this - if that helps?  Depends if you have a Windows box.

**Comment by Jerbell** [comment]
Might be a bit of a Gradle issue, though it seem peculiar that it happens with KTEs and not JTEs.
https://github.com/gradle/gradle/issues/937

**Comment by edward3h** [comment]
Can you try testing with the gradle daemon disabled and see if that makes a difference? 
https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon

**Comment by casid** [comment]
@Jerbell I'm not very deep into Gradle unfortunately and may be of little help. On Windows such behavior usually means that file handles are not properly closed.

The code generation file handling is the same for jte and kte templates.

This kind of indicates that it may be related to the Kotlin compilation. Maybe the Kotlin compiler I'm using isn't properly released / leaks resources and that leads to the behavior you see with the Gradle deamon.

**Comment by casid** [comment]
Looks like it could be this open issue with the Kotlin compiler:
https://youtrack.jetbrains.com/issue/KT-35394

The setting talked about there is this one:
https://github.com/JetBrains/kotlin/blob/e7c4121e6785d1ac4cd7633066b4662ea3a23248/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment.kt#L494

Which then calls that dispose method:
https://github.com/JetBrains/kotlin/blob/e7c4121e6785d1ac4cd7633066b4662ea3a23248/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/KotlinCoreEnvironment.kt#L513-L523

The comment there could explain why it does not happen on Kotlin compilation through the kotlin compiler gradle plugin:

```kotlin
/**
 * This method is also used in Gradle after configuration phase finished.
 */
fun disposeApplicationEnvironment() {
```

You could try to pass the property `kotlin.environment.keepalive=false` to the jte-gradle-plugin, maybe that will be picked up by the compiler?

**Comment by Jerbell** [comment]
> Can you try testing with the gradle daemon disabled and see if that makes a difference?
> https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:disabling_the_daemon

No problems (no lock) when I disable the daemon.

**Comment by Jerbell** [comment]
The `kotlin.environment.keepalive=false` seems to work as well.
```kotlin
tasks.precompileJte {
  System.setProperty(KOTLIN_COMPILER_ENVIRONMENT_KEEPALIVE_PROPERTY, "false")
  sourceDirectory = Path.of(project.projectDir.absolutePath, "src", "main", "jte")
  targetDirectory = Path.of(project.projectDir.absolutePath, "build", "resources", "main")
  compilePath = project.the<SourceSetContainer>()["main"].runtimeClasspath
  contentType = gg.jte.ContentType.Html
  dependsOn(tasks.compileKotlin)
}
```

Perhaps this should be the responsibility of the plugin?

Thanks for tracking down the solution :)

**Comment by casid** [comment]
I've pushed the a `System.setProperty("kotlin.environment.keepalive", "false");` to the gradle and maven compiler. I think mvnd will have the same problem on windows.

Glad you got it working! I'm gonna close this issue, feel free to reopen if there's something still missing 👍
