### ISSUE TITLE
After updating t `1.10` dependencyUpdates taking forever.

### ISSUE THREAD

**Issue by sureshg** [casid/jte#84]
- Setup
    -  `com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.38.0`
    -  `gg.jte:jte:1.10.0`
    -  Gradle - `7.0.2`
    - JDK 17 EA build

After updating to the latest release `./gradlew clean dependencyUpdates` task is stuck forever 

```
> Task :cleanGenerateJte UP-TO-DATE
Caching disabled for task ':cleanGenerateJte' because:
  Caching has not been enabled for the task
Task ':cleanGenerateJte' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
:cleanGenerateJte (Thread[Execution worker for ':',5,main]) completed. Took 0.01 secs.
<===----------> 25% EXECUTING [30s]
> Resolve files of :runtimeClasspath
```

I am not sure whether this is a Gradle or Version plugin issue. Reporting it here because downgrading to `1.9.0` works as expected with the same Gradle and versions plugin.

```
 - gg.jte:jte [1.9.0 -> 1.10.0]
     http://jte.gg
```

**Comment by edward3h** [comment]
Possibly related to my gradle plugin changes. What does your build.gradle look like? What if you run `clean` and `dependencyUpdates` as separate commands?

**Comment by sureshg** [comment]
Interesting, it's the `clean` task that gets stuck.

```bash
 » ./gradlew clean                                                                                                                    
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
<====---------> 33% EXECUTING [8s]
> Resolve files of :runtimeClasspath

```
Here is the sample build script - https://github.com/sureshg/okhttp-jdk-test/blob/main/build.gradle.kts#L9

**Comment by casid** [comment]
@sureshg thanks for the update!

Are you running on Windows? Usually an endless clean implies that there's a file handle somewhere that got not properly closed.

@edward3h do you have an idea what could be the problem? My gradle knowledge is unfortunately not very good...

**Comment by sureshg** [comment]
@casid No, it's on macOS

```
------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          17-loom (Oracle Corporation 17-loom+7-342)
OS:           Mac OS X 11.4 x86_64
```

**Comment by casid** [comment]
Oh nice, then I can try to reproduce the issue on my macbook.

Also, awesome that you're already running the loom preview! :-)

**Comment by edward3h** [comment]
I'll try and take a look over the weekend

**Comment by casid** [comment]
Interesting! I've checked out your example repository. The same thing you describe happens on my MacBook. A gradle clean just hangs forever.

However, when running against 1.11.0-SNAPSHOT, everything works normally. I tried a few times back and forth, but it definitely seems to be fixed now.

To be honest, I have no idea why this is. The only change to the gradle plugin, has been this commit https://github.com/Jerbell/jte/commit/5db53df8e193e27fcf7510a4dd0c715e56091440 (For this issue https://github.com/casid/jte/issues/78)

I was planning to release 1.11 the next days anyways. I'll try to release it today - let's see if it works on your end, too @sureshg .

**Comment by casid** [comment]
@sureshg 1.11.0 is now available on maven central and in the gradle plugin repository.

Let me know if it works on your end with the latest version.

**Comment by sureshg** [comment]
Awesome... It's fixed in `1.11.0`. Thanks for all the help

**Comment by casid** [comment]
Awesome, thanks for testing it so quickly! 👍

**Comment by edward3h** [comment]
Heh, thanks for fixing it before I got around to looking ;)
