### ISSUE TITLE
Set UTF-8 encoding as default when compiling Java templates via jte-maven-plugin precompile goal

### ISSUE THREAD

**Issue by izogfif** [casid/jte#86]
When I use `jte-maven-plugin` in a project with .jte files containing typographic quotes / inverted commas / whatever they are called (e.g. „…“), I get a compile-time error.
```JtesamplePageGenerated.java:961: error: unmappable character (0x9D) for encoding windows-1252```
My system encoding is Windows-1252. Looks like it is applied to Java compiler (`javac`?) that `jte-maven-plugin` runs under the hood during `precompile` goal.
I had to add
```<compileArgs>-encoding,UTF-8</compileArgs>```
in `<configuration>` section of the plugin to make it work. It would be nice if:
* `jte-maven-plugin` set UTF-8 as source encoding for compiler when compiling generated Java files.
* If this is impossible (e.g. breaks backward compatibility for whatever reason), then it would help if `jte-maven-plugin` had a separate property `sourceEncoding` I could specify in `<configuration>` section, instead of writing `<compileArgs>-encoding,ENCODING_NAME</compileArgs>`.

I haven't used runtime template generation on a Windows yet, but I suppose I'll get the same error if I'll try to use `TemplateEngine` to process .jte file in runtime.

**Comment by casid** [comment]
Yes, UTF-8 should be the default for the compiler, not the platform encoding. I'll have a look at it some evening this week.

**Comment by casid** [comment]
I set the default encoding in jte's Java compiler, so this applies to Maven, Gradle and ad-hoc compilation. jte generates Java classes always as UTF-8, so it makes a lot of sense to ensure that the compiler always tries to read UTF-8 👍
