### ISSUE TITLE
jte-maven-plugin's precompile goal leaves .java files next to compiled .class files

### ISSUE THREAD

**Issue by izogfif** [casid/jte#87]
I don't want .java files next to .class files generated during `jte-maven-plugin`'s precompile goal. I want only .class and .bin files. Delete those generated .java files once compilation succeeds. Alternatively, provide a flag that can be specified in `<configuration>` section of the plugin.

**Comment by casid** [comment]
@izogfif would it help to be able to configure a directory where .java files should be placed?

If nothing provided (current default), the same directory would be used.

**Comment by izogfif** [comment]
@casid 

> would it help to be able to configure a directory where .java files should be placed?

Right now I deal with those .java files by invoking `maven-clean-plugin` that finds and removes all .java files from the target folder. Adding a "folder for intermediate .java files" option would require me to clear that folder instead.
I don't want to deal with those files at all. I suggest to add a `keepGeneratedJavaFiles` option with default value `false`. If it's `true`, then keep those .java files.

**Comment by casid** [comment]
@izogfif, understood, thanks for the clarification! I added a property `keepGeneratedSourceFiles` as you suggested. Would you like to have a look? https://github.com/casid/jte/commit/2e99f9118602cad862a0fbbad2b152136cc735a5

**Comment by izogfif** [comment]
@casid it works, thanks.

**Comment by casid** [comment]
Thanks for the quick test and confirmation 👍
