### ISSUE TITLE
jte-maven-plugin should write precompiled classes in targetDirectory instead of targetDirectory/classes

### ISSUE THREAD

**Issue by izogfif** [casid/jte#88]
If I write `<targetDirectory>/my-path</targetDirectory>` inside `<configuration>`, the generated .class, .bin, and .java files are written into `/my-path/classes` instead. It should be exactly what's written inside `<targetDirectory>`

**Comment by izogfif** [comment]
My bad, `/classes` crept into via invalid environment option (I actually wrote `<targetDirectory>${some.path}</targetDirectory>` which was set via environment variables to `/my-path`).

**Comment by casid** [comment]
Thanks for the follow up!
