### ISSUE TITLE
Use maven-compiler-plugin Java version when compiling Java templates via jte-maven-plugin precompile goal

### ISSUE THREAD

**Issue by izogfif** [casid/jte#89]
I've added `jte-maven-plugin`, specified `precompile` goal, got .class files, uploaded them to web server, tried opening the web page and got error. Checking web server logs revealed that `jte-maven-plugin` uses default Java version when compiling JTE templates. 
I use Java 16. In my `pom.xml` I have
```
<java.version>15</java.version>
<maven.compiler.source>${java.version}</maven.compiler.source>
<maven.compiler.target>${java.version}</maven.compiler.target> 
```
Java 15 is installed on the web server, so I get `unsupported class file major version 60`

**Comment by casid** [comment]
Hey @izogfif, thanks for reporting! I think I've pushed a fix for this https://github.com/casid/jte/commit/9fa706b21ad8d81ffcecd66ebae4f42b23b7d10e.

Could you give it a try if this works on your end?  For this you'd need to run against the latest snapshot release `1.11.1-SNAPSHOT`:
- clone this repository
- run mvn clean install
- use `1.11.1-SNAPSHOT` as jte version

**Comment by izogfif** [comment]
Not sure, but maybe `maven.compiler.release` property support should be added as well: https://www.baeldung.com/maven-java-version#java9

**Comment by casid** [comment]
@izogfif thanks for checking it out! You are right, we should definitely support the new --release option, too. I pushed a new commit with this change (https://github.com/casid/jte/commit/c4d46b6489aeef335faa0e501c8bc31ec74b8e47). In case the release option is set, I only pass that and ignore source/target (https://docs.oracle.com/en/java/javase/14/docs/specs/man/javac.html#option-release).

**Comment by izogfif** [comment]
@casid checked, `maven.compiler.release` variable works.

**Comment by casid** [comment]
Thanks for checking!

I'll soon publish a `1.11.1` bugfix release to central and let you know when it's available.

**Comment by casid** [comment]
Just released `1.11.1` to central.

**Comment by izogfif** [comment]
@casid Could you also release `jte-jsp-converter` there? It's not really convenient to fork the repository / install this module manually on local machine.

**Comment by casid** [comment]
Good idea! I added the `jte-jsp-converter` module to the parent pom, so that it will be automatically deployed with each central release in the future.

For the current version I've manually pushed it to central, it should be available within the next hour.
