### ISSUE TITLE
JteStringContent is nowhere to be found

### ISSUE THREAD

**Issue by izogfif** [casid/jte#90]
On https://github.com/casid/jte/blob/master/jte-jsp-converter/README.md page there is `JteStringContent` class in sample code. What's the source code for this class?

**Comment by casid** [comment]
Good catch!

I've updated the readme: https://github.com/casid/jte/commit/4e5e6cf246b0ae50d0a93b3dfec03dabcca66fef

**Comment by izogfif** [comment]
@casid I see, thanks.
