### ISSUE TITLE
Precompilation of JTE files located inside paths with symbolic links

### ISSUE THREAD

**Issue by izogfif** [casid/jte#92]
I re-use JTE templates between multiple Maven modules. In order to avoid code duplication, I put all .jte files inside templates folder, then create symlinks. During Maven build I invoke `precompile` goal of `jte-maven-plugin`. Turns out, it successfully finds and processes .jte files located inside symlinked folder on Windows, but ignores it on Ubuntu.
Suggestion: add `FileVisitOption.FOLLOW_LINKS` in `jte/src/main/java/gg/jte/resolve/DirectoryCodeResolver.java`:
replace 
```try (Stream<Path> stream = Files.walk(root)) {```
with
```try (Stream<Path> stream = Files.walk(root, FileVisitOption.FOLLOW_LINKS)) {```
Maybe hide it behind an option (i.e. `jte-maven-plugin` configuration option).

**Comment by casid** [comment]
Good idea! I adjusted the `DirectoryCodeResolver` as you suggested. I think we don't need a separate option for it, as this is a sane default.
