### ISSUE TITLE
Error in @import directive during JSP to JTE conversion with IDEA plugin

### ISSUE THREAD

**Issue by izogfif** [casid/jte#96]
When converting with Intellij IDEA plugin a JSP .tag file containing
<pre><%@ attribute name="attrName" required="true" type="my.package.CustomType[]" %></pre>
I get .jte file with 
<pre>
@import my.package.CustomType[]
@param CustomType[] attrName
</pre>
There is an error in the first line. There should be no square brackets in type name.
There is also an issue with generics, i.e.
```
<%@ attribute name="attrName" required="true" type="my.package.CustomGeneric<my.package.CustomType>" %>
```
is transformed into
```
@import my.package.CustomGeneric<my.package.CustomType>
@param CustomType> attrName
```
(yes, there is a ">" after "CustomType" in `@param`) instead of
```
@import my.package.CustomGeneric
@import my.package.CustomType
@param CustomGeneric<CustomType> attrName
```

**Comment by casid** [comment]
I've got a fix for it. The generic bean can become arbitrarily complex with import though, so I just skipped them. Feel free to provide a pull request if you'd like to improve that, though ;-)

`@param my.package.CustomGeneric<my.package.CustomType> attrName`
