### ISSUE TITLE
Some kind of "no JTE" text block

### ISSUE THREAD

**Issue by izogfif** [casid/jte#98]
My .jte template consists of plain text interspersed with JTE blocks (e.g. `@if`, `${val}` etc.). If this text is large and contains JTE-reserved symbol sequences like `${`, I have to put these sequences inside JTE blocks, e.g. 
<pre>str.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\$1")</pre>
becomes
<pre>${"str.replace(/([.*+?^=!:\\${\u007D()|\\[\\]\\/\\\\])/g, \"\\\\$1\")"}</pre>
I'd like to have some kind of "no JTE" block so I can avoid unnecessary escaping (and it's a lot of escaping for large code blocks) and write something like this:
<pre>@nojte
str.replace(/([.*+?^=!:${}()|\[\]\/\\])/g, "\$1")
@endnojte</pre>

**Comment by casid** [comment]
Do you generate HTML Pages or plain text? With HTML I used to get away with this by using something like `&#36;` for the $.

**Comment by casid** [comment]
Generally, I'm trying to keep jte as slim and with as few keywords as possible. Maybe we need a way to somehow escape jte keywords? For instance, with your example we could run into problems, too:

```
@nojte
Hey this new feature can be used like this @nojte ... @endnojte... oops.
@endnojte
```

But I'm not sure what a good general purpose escape character would be.

**Comment by izogfif** [comment]
@casid
> Do you generate HTML Pages or plain text? 

HTML files are generated. Some of them contain inline `<script>` tags with JavaScript code. And this JavaScript code might contain `${` character sequences. Hence I got away with `\u`-escape.

> For instance, with your example we could run into problems, too
> 
```@nojte
Hey this new feature can be used like this @nojte ... @endnojte... oops.
@endnojte
```

I think it is highly unlikely that `@nojte` text appears inside the user code/text (I'm not talking about sample documentation for JTE). But it's a good idea to pick some extremely-unlikely-to-be-used sequence of characters as JTE keyword (e.g. `@jte_plain_text_block` or something like that). It might be a little bit long, just to reduce the chance that it'll be contained inside the code it wraps around. 

As an extreme measure a boundary can be defined, like in [HTTP multipart](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#content-type_in_html_forms) request:
```
@nojte(boundary_text)
Hey this new feature can be used like this @nojte ... @endnojte... oops.
@endnojte(boundary_text)
```
I'd say it would be better to make it optional, i.e. if no boundary is specified, then just use `@nojte ... @endnojte`.

**Comment by casid** [comment]
I'm closing this for now, since HTML escaping seems like a reasonable workaround.
