### ISSUE TITLE
JSP Converter - Bug in JSP tag usage detection

### ISSUE THREAD

**Issue by izogfif** [casid/jte#99]
If I JSP tag library is imported under different prefixes in different .jsp / .tag files, its usage is detected incorrectly. 
For example, `/WEB-INF/tags/modals/user.tag` is used in `file1.jsp` with prefix "modal"
```
<%@ taglib prefix="modals" tagdir="/WEB-INF/tags/modals" %>
<modals:user/>
```
In `file2.jsp` the same .tag file is used as
```
<%@ taglib prefix="dialogs" tagdir="/WEB-INF/tags/modals" %>
<dialogs:user/>
```
(note prefix "dialogs" instead of "modals").
Technically the file is the same, but only `<modals:user/>` is recognized by `jte-jsp-converter` (and, subsequently, Intelij IDEA jte plugin).

**Comment by casid** [comment]
Interesting. Would you like to provide a PR with a fix for it?

**Comment by casid** [comment]
Closed, as its possible to properly name taglib imports before doing the conversion.
